### DISCUSSION TITLE
Question: Can I use a custom subdomain for preview deployments?

### DISCUSSION THREAD

**Discussion by dgokcin** [vercel/community#1056] [Help] [answered]
Hello

TL;DR: Can I point a subdomain to the **latest** preview deployment using vercel cli and/or aliases without the GitHub integration such that promoting a build to production does not overwrite anything?

I am using Cloudflare for managing my domain example.com. I have a vercel project set up without the Git Integration and I have two domains(example.com and qa.example.com) that I added to vercel. Both of the domains are shown as _**production**_ under project settings -> domains. 

When I build with `vercel build` and deploy with `vercel deploy  --prebuilt` on the _develop_ branch, and set an alias of the deployment to `qa.example.com`, this creates a preview deployment on Vercel UI, which is what I expect. However, if I build with `vercel build --prod`,`vercel deploy --prod --prebuilt` and set an alias to example.com on my _main_ branch, although example.com works as I expected, I see that qa.example.com looks the same as example.com. Is this expected and documented somewhere? If not how can I configure vercel to not do that?

Thanks

**Comment by amyegan** [comment, marked as answer]
Hi @dgokcin! It is expected that all custom `Production` [domains](https://vercel.com/docs/concepts/projects/domains#) take you to the latest production deployment. 

You can set up a [branch-specific subdomain](https://vercel.com/docs/concepts/projects/domains/assign-domain-to-a-git-branch#) as a staging domain. That wouldn't apply to all preview deployments, but would work for any deployed from a staging branch. Then `qa.example.com` would become a `Preview` domain and show the staging version of your site, while `example.com` would be your `Production` domain and show the production version.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/8247105/202035635-b11f34c4-3677-4ea0-ae99-80201d34cc98.png">

You can learn more about how to set up a staging environment here: [vercel.com/guides/set-up-a-staging-environment-on-vercel](https://vercel.com/guides/set-up-a-staging-environment-on-vercel)

**Reply by dgokcin** [reply]
Thanks for the reply. One question though, will connecting my vercel project to git cause me additional costs in the pro plan(like 20USD per commiter)

**Reply by dgokcin** [reply]
@amyegan also if the answer is yes for the above question, would using `vercel deploy --prebuild` without the `--prod` option in both of my deployments(qa and prod) will cause a problem othet than not being able to promote a preview deployment from vercel ui?

**Reply by amyegan** [reply]
There is no additional charge for [connecting git repository to your Vercel Project](https://vercel.com/docs/concepts/git#). I use [Vercel for GitHub](https://vercel.com/docs/concepts/git/vercel-for-github#) a lot for my hobby projects and find it very convenient for most use cases. 

If you want to know more about the features that may cause additional charges, you can find more details on the [Limits](https://vercel.com/docs/concepts/limits/overview#), [Usage](https://vercel.com/docs/concepts/limits/usage#), and [Fair Use Policy](https://vercel.com/docs/concepts/limits/fair-use-policy#) pages.

---

I might be misunderstanding your second question. Please correct me if got it wrong!

All production builds can only be deployed to the production environment. And all preview builds can only be deployed to the preview environment. If you do a production build and try to deploy it without the `--prod` option then you will get an error like this:
```
Error: The "--prebuilt" option was used with the target environment "preview", but the prebuilt output found in ".vercel/output" was built with target environment "production". Please run `vercel --prebuilt --prod`.
Learn More: https://vercel.link/prebuilt-environment-mismatch
```

If you are comfortable with a more complex setup, the CLI can give you more flexibility for your preview deployment domain. You could use [`vercel alias`](https://vercel.com/docs/cli/alias#) to add a custom staging domain to your preview deployments. The production domain is automatically applied to the latest production deployment in any case.

There are some guides available to walk you through basic automation setup with Vercel CLI for [GitHub Actions](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel), [GitLab Pipelines](https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel), and [Bitbucket Pipelines](https://vercel.com/guides/how-can-i-use-bitbucket-pipelines-with-vercel) if you're interested in that approach.

**Reply by dgokcin** [reply]
Hello @amyegan thanks for the reply

So we are under the team plan and the domains are configured under the pro team , not under hobby personal account since we want the usage limitations in the personal account is not enough for us. What I read in [here](https://vercel.com/docs/concepts/git#using-teams) makes me think that If I am in the teams scope, I will get charged 20 USD per commiter if I enable the git integration even though I am building on GitHub actions deploying using the vercel CLI with the `--prebuild` argument. Is this correct or I can just connect my qa.example.com domain to the develop branch and deploy to the qa.example.com preview environment like the screenshots you have shared without any additional costs?

In this case, you can ignore my second question :). Would connecting qa.example.com to github develop branch wil result like the screenshot you have shared(qa.example.com -> preview) without any additional costs in the team plan after the following workflows execute(assuming that it already deploys correctly to the qa.example.com production domain)?

```yml
name: Deploy to Vercel QA
on:
  workflow_dispatch:
  repository_dispatch:
    types: deploy_to_qa
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MY_WEBSITE_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_GHA_TOKEN }}
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
  NODE_VERSION: 16
  ENVIRONMENT: qa
  VERCEL_ENV: preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.target_branch || github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Pull Project Settings from Vercel
        run: yarn vercel pull --yes --environment=${{ env.VERCEL_ENV }} --token=${{ env.VERCEL_TOKEN }}

      - name: Pull Environment Variables from Vercel
        run: yarn vercel env pull --environment=${{ env.VERCEL_ENV }} --yes --token=${{ env.VERCEL_TOKEN }} .env.local

      - name: Move .env.${{ env.ENVIRONMENT }} to .env
        run: mv .env.${{env.ENVIRONMENT}} .env

      - name: Vercel Build
        run: yarn vercel build

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: --archive=tgz --prebuilt
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID}} #Required
          scope: ${{ env.VERCEL_TEAM_ID }} #Optional
          alias-domains: |
            qa.example.com
```

```yml
name: Deploy to Vercel PROD
on:
  workflow_dispatch:
  repository_dispatch:
    types: deploy_to_prod
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_MY_WEBSITE_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_GHA_TOKEN }}
  VERCEL_TEAM_ID: ${{ secrets.VERCEL_TEAM_ID }}
  NODE_VERSION: 16
  ENVIRONMENT: prod
  VERCEL_ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.target_branch || github.ref }}
          fetch-depth: 0

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Bump version and push tag
        id: versioning
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          WITH_V: true
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          # cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Pull Project Settings from Vercel
        run: yarn vercel pull --yes --environment=${{ env.VERCEL_ENV }} --token=${{ env.VERCEL_TOKEN }}

      - name: Pull Environment Variables from Vercel
        run: yarn vercel env pull --environment=${{ env.VERCEL_ENV }} --yes --token=${{ env.VERCEL_TOKEN }} .env.local

      - name: Move .env.${{ env.ENVIRONMENT }} to .env
        run: mv .env.${{env.ENVIRONMENT}} .env

      - name: Vercel Build
        run: yarn vercel build

      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ env.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: --archive=tgz --prebuilt --prod
          vercel-org-id: ${{ env.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ env.VERCEL_PROJECT_ID}} #Required
          scope: ${{ env.VERCEL_TEAM_ID }} #Optional
          alias-domains: |
            example.com
```
