### DISCUSSION TITLE
Unable to import dependency via "file:../foo" from neighbor directory in monorepo

### DISCUSSION THREAD

**Discussion by corygabrielsen** [vercel/community#1229] [Help]
### Summary

Hello, I have a private repo with the following challenge:

```
example/
example/foo/
example/foo/package.json
example/bar-depends-on-foo/
example/bar-depends-on-foo/package.json
```

With the relevant sections of `package.json`s being:
```json
  "name": "@example/foo",
```
and
```json
  "name": "@example/bar-depends-on-foo",
  "devDependencies": {
    "@example/foo": "file:../foo",
```

The `bar-depends-on-foo` in this case is where the web application lives and what Vercel is trying to load.

On GitHub CI and Codespaces and my local machine, it is happy with this setup. But Vercel fails at `yarn install`. 

The application is entirely written in NodeJS, it just links between neighbor directories for code organization and re-use.

Do you know if I can solve this without publishing my package yet? The build system is more fault tolerant by linking locally via `../neighbor_dir` file reference than by publishing as a separate npm module which is a lot of overhead.

**Comment by swarnava** [comment]
Do you have a deployment url which we can take a look?

**Comment by corygabrielsen** [comment]
Here is a link to a failed deployment: https://vercel.com/stoooops/openavatar/C1q9rMYyHmPw3ohWRbsYpH4XWh5u

The build succeeds on GitHub CI using the same target:
![image](https://user-images.githubusercontent.com/3518037/211370190-871374e9-d619-4c83-a9cb-023f94804541.png)

Here is what the `.github/workflows/ci.yml` looks like. There are no environment variable dependencies or otherwise, just the local neighbor directory linking.

```yml
name: CI

on: [push]

jobs:
  # This CI builds sprites with python, fast
  # the idea is to be able to keep the python/NodeJS
  # builds in sync so that the web app can be deployed
  # to services supporting NodeJS, but still have
  # faster build script available locally
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn coverage

  # This CI builds sprites with NodeJS
  # this is slower
  # useful for NodeJS hosting
  build-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      # avoid triggering python build script, slower
      - run: yarn build:node
      - run: yarn test
```

Given that the same command works on GitHub CI (with no special configuration) but not on Vercel, I am led to believe this is indeed an issue on Vercel side.

I don't want to redo my build system again, so I will have to explore GitHub Pages or find the bug in my code causing this issue.
