### DISCUSSION TITLE
How to set the git branch when using gitlab CI

### DISCUSSION THREAD

**Discussion by matthew-walters** [vercel/community#1246] [Help] [answered]
### Summary

I'm following this section
https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel#configuring-gitlab-ci/cd-for-vercel

My gitlab ci `build `stage contains
```
  script:
    - yarn exec vercel -- pull --yes --environment=preview --git-branch=$CI_COMMIT_BRANCH --token=$VERCEL_TOKEN
    - yarn exec vercel -- build --token=$VERCEL_TOKEN
  artifacts:
    paths:
      - .vercel/output
    expire_in: 1 hour
```

And later in the `deploy` stage:
```
  script:
    - yarn exec vercel -- deploy --prebuilt --token=$VERCEL_TOKEN
 ```

In the Vercel UI - Deployments, I see my deployment `via Vercel CI`, but when I click the link, under Branch, it says `No repository.
