### DISCUSSION TITLE
Hugo deployment ignores markup.tableOfContents settings

### DISCUSSION THREAD

**Discussion by mitjafelicijan** [vercel/community#1318] [Help]
### Summary

When I deploy to Vercel with Hugo as a Present framework, the following setting are being ignored. It works locally, though.

```toml
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 2
```

The Vercel deployment also creates sub navigation of H3.

Any ideas why this would be happening?

### Additional information

Locally I am running `hugo v0.98.0+extended linux/amd64 BuildDate=unknown`.
