### DISCUSSION TITLE
Google Auth 2.0 redirect URI with Vercel preview deployment

### DISCUSSION THREAD

**Discussion by emadabdulrahim** [vercel/community#132] [Help] [answered]
Google Auth 2.0 doesn't allow for use of wild card (*). How could I make auth work on my NextJS app for Vercel preview deployment when the url is dynamically generated, and Google wants hardcoded whitelist?

**Comment by dfjs** [comment, marked as answer]
@emadabdulrahim if you're working on a branch you could create an alias for that branch in Domain settings, or even just use the Vercel generated branch env name, both of which you can add to your whitelist, rather than using specific deployments for testing this

**Reply by emadabdulrahim** [reply]
Thanks, @dfjs. I'll try that.

**Reply by NurbekGithub** [reply]
Sorry, I cannot quite find information about neither alias for branch nor Vercel generated branch env. So I still have the error. Could you elaborate more on this please?

**Reply by torkue** [reply]
I connected a subdomain for the Vercel project's preview and it seems to work otherwise except for the Google sign-in. I'm getting an error about unauthorized redirect URL that points to the dynamic one generated by Vercel. 

I'm stuck trying to find a solution. Maybe I need to create a custom sign-in page? Currently I've been using the one that comes with NextAuth by default. The only way I've been able to test the logins in preview is to go in Google's settings and whitelist the dynamic URL every time.

**Comment by utsavdotpro** [comment]
This seems like an ideal solution:

Create `NEXTAUTH_URL` environment variable in your vercel app

    NEXTAUTH_URL=https://your-next-auth-repo.vercel.app

Also, make sure that you have `https://your-next-auth-repo.vercel.app` added under **Authorized redirect URIs** on your Google Cloud Console

_Credit: [this](https://github.com/nextauthjs/next-auth/issues/3419#issuecomment-991802423) comment_

**Comment by wtachau** [comment]
For anyone still working on this: I got the `alias` cli command to work with a github action that lets me alias `previous.company.com` to the latest vercel preview URL
```yml
name: Assign Vercel Preview

on:
  deployment_status:

jobs:
  bar:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Update Vercel Preview
        run: vercel alias set ${{ github.event.deployment_status.target_url }} preview.company.com --token=${{ secrets.VERCEL_TOKEN }} --scope <vercel-org>

```
