### DISCUSSION TITLE
How to specify vercel builds location ?

### DISCUSSION THREAD

**Discussion by ArnaudD** [vercel/community#1470] [Help]
### Summary

I recently noticed that my builds were running in San Francisco in the first line of the build log:

```
Running build in San Francisco, USA (West) – sfo1
...
```

My database & API are in europe, is it possible to specify a different build location in order to be closer to our data ?

I already have `regions: ["cdg1"]` (Paris) in my `vercel.config`, running the builds there would be nice.

**Comment by ruchernchong** [comment]
I have the same concerns as you too. I would love to have my builds running at my desired location rather than a default one in SFO.

I hope more responses will get visibility for the Vercel team to respond to this.

**Comment by amyegan** [comment]
Hi! When projects are deployed to the [Edge Network](https://vercel.com/docs/concepts/edge-network/overview#), the build location shouldn't make a difference. 

Can you tell me more about your concerns, and what you want to achieve with a customized build location? If there is not already a solution to suit your needs, then I'll need more info to share with the team 🙏

**Reply by bonesoul** [reply]
Same issue here, should be able to run builds in Europe. 

The main concern is my build process do have migration & seeding steps. Even though my edge config is set to europe and my db is europe too, the build is running in San Francisco which makes my db inserts & updates very slow. (detailed here: https://github.com/orgs/vercel/discussions/1529)

**Reply by aotng** [reply]
Hi,I am in East Asia,but it build in USA.It seem makes a funny thing,Vercel building status tell me it skip my some pages because _Skipping: _posts/2023-06-06-ChineseTest.md has a future date_

**Reply by ruchernchong** [reply]
> Hi,I am in East Asia,but it build in USA.It seem makes a funny thing,Vercel building status tell me it skip my some pages because _Skipping: _posts/2023-06-06-ChineseTest.md has a future date_ 

This is certainly a problem for people in different time zones.

**Reply by amyegan** [reply]
Hi @ruchernchong. When determining future dates, does your app compare with UTC or does it assume a specific local time zone?

**Comment by ArnaudD** [comment]
Hi @amyegan, thanks for your answer. I know that I should be doing it differently but for now we are prerendering approximatively 5000 pages at build time (only in production). Building takes 18min from SF and 6min from europe on our servers. Even though our build servers are probably more powerful than the default ones at vercel, I suppose that latency between SF and Paris plays a role in this.

With (at least) 2 requests to our API per page built and 90ms of added latency per request (round trip from Paris to SF at the speed of light), this should add 16min to our builds. Seems huge, but I can't see were my calculations are wrong.

**Comment by ashburnham** [comment]
Same here - we build 15,000 pages at build time.. and it takes 15 mins from London... but it times out from SF due to the round trip.

Can we build our projects in the region we specify our serverless functions are in, please?

**Comment by tothonx** [comment]
It would be great to choose the region for the builds 👍

**Reply by thereis** [reply]
I'm still waiting!

**Comment by dansmachina** [comment]
Any news on this?

**Comment by luke-maddox** [comment]
Same question here.

**Comment by justoverclockl** [comment]
same here

**Comment by huksley** [comment]
Yes, build region should be configurable. I use production data from DB in eu-west-1 (Dublin) region

**Comment by mirik999** [comment]
same here

**Comment by mayrsascha** [comment]
I'm really disappointed in Vercel on this one. Builds with a lot of pages will 100% time out if the connected database isn't close to the default region and this seems like a rather simple fix on your side since the serverless function region can already be changed...

**Comment by sarbloc** [comment]
We need this feature! An api I'm using is blocked in US regions and I need to use it server-side in my next js app, so I'm stuck.

**Reply by Thiago-Mota-Santos** [reply]
Use vercel cli commands 

e.g

vercel --regions gru1

https://vercel.com/docs/cli/deploy#regions

**Comment by l3wi** [comment]
Same here, I'm getting build errors due to getting geoblocked during prerenders.

cc. @amyegan

**Reply by Thiago-Mota-Santos** [reply]
https://vercel.com/docs/cli/deploy#regions

**Comment by samparmenter** [comment]
This is causing us issues as well. With a few thousand pages this latency isn't helping matters.

**Comment by amyegan** [comment]
Reading through the comments, it looks like a lot of folks here are running into trouble when **building a large number of pages**. While the location of builds is not configurable on Pro and Hobby plans, it looks like that would not completely solve some of the issues I’ve seen reported here anyway. I have a couple of other ideas that may help.

If your Next.js app happens to use `getStaticPaths` to return a lot of paths, that can cause problems for builds in any region, even those very near to the data source. If you change the app configuration to [generate some paths on-demand](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-paths#generating-paths-on-demand) the build time can be reduced.

Aside from just Next.js, [Incremental Static Regeneration (ISR)](https://vercel.com/docs/incremental-static-regeneration#) can be used with other frameworks for faster builds. And you can [choose the serverless function region in project settings](https://vercel.com/docs/functions/configuring-functions/region) to keep function execution close to your data source. 

There are also options to build the project elsewhere and push the prebuilt code. One option is an automated workflow tool such as [GitHub Actions](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel) or [GitLab Pipelines](https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel) or [Bitbucket Pipelines](https://vercel.com/guides/how-can-i-use-bitbucket-pipelines-with-vercel). Another option is local Vercel CLI which lets you [deploy from a local build](https://vercel.com/docs/cli/deploying-from-cli#deploying-from-local-build-prebuilt) with the option to [compress deployment code into a single file](https://vercel.com/docs/cli/deploy#archive) before uploading.

**Reply by ismaeliberal** [reply]
Hi, thanks for your replay, all the things that you propose are very interesting for reduce the build time, but i have some questions:

How many paths are "a lot"?

Are there any plan in the near future to change between region for the builds?

Thanks!

**Reply by samparmenter** [reply]
We ran into issues around 1600 pages with the builds timing out.

**Reply by weiskopfsodefa** [reply]
"While the location of builds is not configurable on Pro and Hobby plans..."
Does that mean it is configurable in Enterprise plan? If yes, where? 
Thanks!

**Reply by amyegan** [reply]
[Vercel Secure Compute](https://vercel.com/docs/security/secure-compute#) is an option for Enterprise customers to put their builds and deployments in a private network.
> By enabling Secure Compute on your Project, your deployments and build container will be placed in a private network with dedicated IP addresses in a region of your choice and logically separated from other containers.

https://vercel.com/docs/security/secure-compute

**Comment by ArnaudD** [comment]
> There are also options to build the project elsewhere and push the prebuilt code. One option is an automated workflow tool such as [GitHub Actions](https://vercel.com/guides/how-can-i-use-github-actions-with-vercel) or [GitLab Pipelines](https://vercel.com/guides/how-can-i-use-gitlab-pipelines-with-vercel) or [Bitbucket Pipelines](https://vercel.com/guides/how-can-i-use-bitbucket-pipelines-with-vercel). Another option is local Vercel CLI which lets you [deploy from a local build](https://vercel.com/docs/cli/deploying-from-cli#deploying-from-local-build-prebuilt) with the option to [compress deployment code into a single file](https://vercel.com/docs/cli/deploy#archive) before uploading.

For thoses interested in implemeting @amyegan suggestions, here is the github action I use to make our builds a little bit faster :

```yml
name: Deploy Website
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.WEBSITE_VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install deps (containing Vercel CLI@28.x.x)
        run: yarn install

      - name: Prod or Preview
        id: prod_or_preview
        run: |
          if [ "$BRANCH" == 'master' ]
          then
              echo "vercel-pull-args=--environment=production" >> $GITHUB_OUTPUT
              echo "vercel-build-args=--prod" >> $GITHUB_OUTPUT
              echo "vercel-deploy-args=--prebuilt --prod" >> $GITHUB_OUTPUT
              echo "domain=www.my-website.com" >> $GITHUB_OUTPUT
          else
              echo "vercel-pull-args=--environment=preview" >> $GITHUB_OUTPUT
              echo "vercel-deploy-args=--prebuilt" >> $GITHUB_OUTPUT
          fi
        env:
          BRANCH: ${{ github.ref_name }}
          RUN_ID: ${{ github.run_id }}

      - name: Pull Vercel Environment Information
        run: yarn vercel pull --scope=${{ secrets.VERCEL_SCOPE }} --yes ${{ steps.prod_or_preview.outputs.vercel-pull-args }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: yarn vercel build ${{ steps.prod_or_preview.outputs.vercel-build-args }} --token=${{ secrets.VERCEL_TOKEN }}

      - uses: amondnet/vercel-action@v25
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.WEBSITE_VERCEL_PROJECT_ID }}
          vercel-args: --archive=tgz ${{ steps.prod_or_preview.outputs.vercel-deploy-args }}
          vercel-version: 28.x.x
          alias-domains: |
            ${{ steps.prod_or_preview.outputs.domain }}
            my-website-${{ github.ref_name }}.vercel.app
            my-website-${{ github.ref_name }}-${{ github.run_id }}.vercel.app
          scope: ${{ secrets.VERCEL_SCOPE }}
```

 It runs on a self-hosted github action runner near our API/Database, making the build (`vercel build` only)  step faster (twice maybe...).
 
But overall, the total time (build + deploy to vercel) is not a lot faster compared to builds on vercel. The deploy step (with https://github.com/amondnet/vercel-action) takes a lot of time, particularly the upload part. I haven't investigated why, but it takes 13m to upload 392M on vercel :

![image](https://github.com/vercel/community/assets/40349/d45158db-ee29-4b36-a2ea-4b2d4a7fa9cb)
