### DISCUSSION TITLE
Running a Python Web Server Properly (FastAPI)

### DISCUSSION THREAD

**Discussion by eeriemyxi** [vercel/community#1568] [Help] [answered]
### Summary

Hello, I am new to Vercel, and I want to run a basic Python web server using the FastAPI library. However, I couldn't collect all the correct pieces from Vercel's website to get it to work.

All this is currently in a private repository and Vercel automatically deploys the repository whenever changes are pushed. When I go to check the URL, [I get a 404 error](https://personal-static-site-ctn23it4a-myxi.vercel.app/).

I have read couple pages on how to use the Python runtime, however it seems that I am missing something crucial. 

### Additional information

```yml
(personal-static-site) eeriemyxi :: coding/python/personal-static-site ‹master› » tree
.
├── LICENSE
├── __main__.py
├── Pipfile
├── __pycache__
│   ├── app.cpython-310.pyc
│   └── __main__.cpython-310.pyc
└── requirements.txt

1 directory, 6 files
```
```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
fastapi = "*"
uvicorn = "*"

[requires]
python_version = "3.9"
```
```py
from fastapi import FastAPI
import uvicorn


app = FastAPI()

@app.get("/")
def root():
    return {"message": "hello world again"}


if __name__ == '__main__':
    uvicorn.run(app)
```
