### DISCUSSION TITLE
Strategy for cleaning up Vercel deployments

### DISCUSSION THREAD

**Discussion by einarpersson** [vercel/community#1659] [Help] [answered]
## Background / context
I'm using a custom github workflow file with the vercel CLI instead of the github autodeploy integeration feature (since I need more control regarding the order of deployment). I have one temporary database deployed for every pull request branch (which is torn down when the PR is closed). A new vercel deployment is created on every push to the pull request branch. In fact this is a bit unnecessary since I really only need one active deployment for every PR at any given time (namely, the latest commit on that branch).

Everything works fine, but the result is that I'm creating a pile of vercel deployments which are never removed and will continue to grow until their mass makes them implode into a black hole. This feels wasteful, and I just don't like the idea of a bunch of URLs hanging around out there with no purpose.

## Question
How can I systematically clean up after myself? I would ideally like to find out

1. A way of removing all deployments for a given branch
2. A way of removing the latest deployment for a given branch so that I can modify my workflow to always only have one existing deployment per pull request branch (nice to have but not necessary)

I'm aware that when running `vercel deploy` the generated deployment url is returned. But it is non trivial to capture these generated urls and store them somewhere in a CI environment and then later in another workflow fetch them.

I expected it to be possible to _"delete all deployments for a given branch"_, or running `vercel list` with some filter specifying a branch or something. I have explored the vercel CLI documentation but it is very sparse to say the least. Take for example [vercel list --meta key1=value1 key2=value2](https://vercel.com/docs/cli/list#meta). Could this maybe be used? I don't know since the available meta data keys are not specified anywhere.

Thank you for any assistance, and please feel free to ask further questions if something is not clear.

## Parts of my workflow file
```
name: Pull request workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

...

deploy-app:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    needs: deploy-db
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Deploy Project Artifacts to Vercel
        run: vercel --env POCKETBASE_URL="https://${{ env.FLY_APP_NAME }}.fly.dev" --token=${{ secrets.VERCEL_TOKEN }}

...

  cleanup:
    if: ${{ github.event.action == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Remove Fly App
        run: flyctl apps destroy ${{ env.FLY_APP_NAME }} -y
      # CLEANUP VERCEL HERE?
```

### EDIT

**Note:** I found a specification for the git metadata [here](https://vercel.com/docs/rest-api#endpoints/deployments/create-a-new-deployment/body-parameters) but when I query the Vercel API I only get either `githubCommitRef": "main"` or  `githubCommitRef": "HEAD"` which doesn't really help.

I also tried setting a metadata key on deploy (which worked!) `vercel --meta foo=${{ env.bar }}` with the hope that this could be used to use it as a flag when looking up and cleaning up deployments. However, the `vercel list <project> --scope <team> --meta foo=bar` is not really useful since it's output is not possible to pipe into a script. And the Vercel API `https://api.vercel.com/v6/deployments` does not even support using meta as a query parameter.

I am lost.
