### DISCUSSION TITLE
Configure Vite's base directory inside Vercel

### DISCUSSION THREAD

**Discussion by VladislavDegtyarenko** [vercel/community#1694] [Help] [answered]
### Summary

Hello,

I've created my [project](https://github.com/VladislavDegtyarenko/vd-developer-portfolio), and trying to deploy it both to **GitHub Pages** and **Vercel**.

The issue is that I can't find a way to set base directory inside Vercel.

Firstly, to successfully deploy the project to GitHub Pages, I configured a base directory in `vite.config.js` to match the repository name:

```javascript
// vite.config.js
export default defineConfig({
  base: "/vd-developer-portfolio/",
  // ...
});
```

And If we visit the [GitHub Pages deployment](https://vladislavdegtyarenko.github.io/vd-developer-portfolio/ 
), It works fine!

However, when I imported and deployed the project to **Vercel**, it showed a blank page with **404 Not Found** error on .js and .css files:
```yaml
GET https://vd-developer-portfolio.vercel.app/vd-developer-portfolio/assets/index-32eff8c9.js net::ERR_ABORTED 404
GET https://vd-developer-portfolio.vercel.app/vd-developer-portfolio/assets/index-6218ca3d.css net::ERR_ABORTED 404
```

The reason is that **Vercel** is trying to access those .js and .css files through that base directory: `/vd-developer-portfolio/`

The info from the Headers tab shows:
```yaml
Request URL: https://vd-developer-portfolio.vercel.app/vd-developer-portfolio/assets/index-32eff8c9.js
Request Method: GET
Status Code: 404 

Request URL: https://vd-developer-portfolio.vercel.app/vd-developer-portfolio/assets/index-6218ca3d.css
Request Method: GET
Status Code: 404 
```

So the question is, how can I make Vercel aware of the base directory? In other words, how can I **set Vite's base directory inside Vercel config**?

The project repository is located at https://github.com/VladislavDegtyarenko/vd-developer-portfolio.
The Vercel domain: https://vd-developer-portfolio.vercel.app/
