### DISCUSSION TITLE
Running E2E tests in response to "deployment_status" event

### DISCUSSION THREAD

**Discussion by yarinsa** [vercel/community#2138] [Help]
### Summary

This is my code structure 
```
├── apps
│   ├── storybook
│   ├── console (Next.js)
├── packages
│   ├── ui
│   ├── eslint
├── E2E (WebDriver.IO)
```

The next.js and Storybook are both vercel projects. There is 2 options to deploy them:
1. Add git integration
2. Do this manually using our workflow

At the moment, Iv'e set up the git integration and it works great. When I was moving to 2 for customized release flow I lost some features that vercel bot offers. Therefor I moved back to solution 1 and created another workflow called "e2e.yml". Which looks as following:
```
# This workflow is triggered when a deployment status is created (or updated) on a deployment with the name "console"

name: Console E2E Tests
run-name: E2E Tests ${{ github.event.deployment_status.environment }}

on: 
  deployment_status:
    
jobs:
    e2e-tests:
        if: ${{ contains(github.event.deployment_status.environment, 'console') }}
        runs-on: ubuntu-latest
        steps:
            ## Prepare
            - name: Get deployment URL
              id: deployment_url
              run: |
                echo Running E2E tests against: ${{ github.event.deployment_status.environment_url }} >> $GITHUB_STEP_SUMMARY
                echo BASE_URL=${{ github.event.deployment_status.environment_url }} >> $GITHUB_ENV

            ## Setup
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node-pnpm

            ## Run test
            - name: Run WDIO
              working-directory: ./e2e
              run: pnpm run wdio
```

## The problem
This workflow is intended to test only the console. As the storybook got another testing logic. 
My issue is that vercel is creating two deployments for each commits one for SB and another for Next.js. Then 
The Next.js check runs first, success, then the SB one is canceled. The result is:
![Screenshot 2023-04-20 at 13 10 55](https://user-images.githubusercontent.com/44482362/233335461-6b5c0beb-e52f-409e-b5f1-45093d1e9c79.png)

Since they are considered as the "same check" one result can override the other and make it false positive. 

Any suggestion of another flow?
