### DISCUSSION TITLE
How can I deploy Development with Actions?

### DISCUSSION THREAD

**Discussion by ManuLpz4** [vercel/community#2178] [Help] [answered]
### Summary

Hey, guys! How is it going? Hope you are doing well :)

I'm trying to deploy my develop branch in every push to 2 environments, one with a custom domain with production envs and the other one with development envs. The issue here is that develop always are deploying with Preview ones.

### Additional information

It seems to deploy a development env but it actually deploys a preview one.

```yaml
name: Vercel Development Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    push:
        branches:
            - develop
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Vercel CLI
              run: npm install --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

```
