### DISCUSSION TITLE
Every deployment breaks CloudFlare cache

### DISCUSSION THREAD

**Discussion by cryptoquick** [vercel/community#2717] [Help] [answered]
### Page to Investigate

beta.bitmask.app

### Steps to Reproduce

Whenever we merge a new feature, webpack cache-busting creates new JS and WASM asset names, and so the old asset is no longer there while CloudFlare is serving a cached copy of the webpage. Is there a way to purge CloudFlare upon successful deployment?

**Comment by smaeda-ks** [comment]
@cryptoquick
> and so the old asset is no longer there while CloudFlare is serving a cached copy of the webpage

If you're caching those static assets on Cloudflare as well (on top of Vercel CDN), they should still be available even after new Vercel deployments, right? It sounds like you need to tune your caching configuration in your Cloudflare setting to cache them longer.

Otherwise, consider disabling caching on Cloudflare.
Or, you can use their REST APIs, and subscribe to our webhook event:
https://developers.cloudflare.com/api/operations/zone-purge
https://vercel.com/docs/integrations/webhooks-overview/webhooks-api#supported-event-types

**Reply by cryptoquick** [reply]
It looks like I need to add an some Request headers for authorization like `X-Auth-Email` and `X-Auth-Key` to the CloudFlare webhook request? Do you know how I can do that in the Vercel UI? Or is there a different way?

**Reply by smaeda-ks** [reply, marked as answer]
@cryptoquick you could have a simple API endpoint that receives our Webhooks requests, then parse the POST body payload and invoke Cloudflare APIs from there. You will need to create a new Vercel integration to do this.

Another approach would be to stop using our GitHub integration (that triggers deployments automatically upon git pushes), and trigger deployments via Vercel CLI from GitHub Actions:
https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

This way, you can easily tell if the deployment is succeeded or failed, then invoke Cloudflare APIs by following that.

**Reply by cryptoquick** [reply]
Good point. I like the suggested modification to the actions, since the Vercel deployment integration often fails to work well anyway, it'll forget to report a successful deployment and then block our review process.

**Reply by cryptoquick** [reply]
After adding this, cache clearing works well:

```yaml
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Purge CloudFlare
        run: 'curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "Authorization: Bearer $CF_API_KEY" -H "Content-Type: application/json" --data "{\"purge_everything\":true}"'
```

The only issue left now is, every deployment leaves our actions hanging:
![Screenshot from 2023-06-15 16-12-55](https://github.com/vercel/community/assets/285690/f39a9c74-5213-469a-a3d0-c17de77f6e2a)
