### DISCUSSION TITLE
Invalid alias when deploying from CLI

### DISCUSSION THREAD

**Discussion by lzzparis** [vercel/community#2830] [Help] [answered]
### Summary

I'm trying to make a preview deployment for my git branch via the Vercel CLI in Github Actions.  I was noticing that Vercel's standard git branch domain alias (`https://<project-name>-git-<branch-name>-<team-name>.vercel.app`) is not automatically getting created for my deployments.  I originally allowed Vercel for Github to handle the deploy, so this link is currently pointing to previously deployed code.

Now I'm trying to set up the alias for each deployment myself via `vercel alias`.  However I get the following error:

```
Run url="$(vercel deploy --prebuilt --token=***)"
  
Vercel CLI 2[9](https://github.com/<reponame>/actions/runs/5246774246/jobs/9476042583#step:9:9).3.3
Retrieving project…
Deploying <team-name>/<project-name>
Uploading [--------------------] (0.0B/763.[9](https://github.com/<reponame>/actions/runs/5246774246/jobs/9476042583#step:9:10)KB)
Uploading [=====---------------] (199.9KB/763.9KB)
Uploading [==========----------] (389.0KB/763.9KB)
Uploading [===============-----] (574.9KB/763.9KB)
Uploading [====================] (763.9KB/763.9KB)
Inspect: https://vercel.com/<team-name>/<project-name>/FGm3CuFWSqwWvSu71Gzk2eqTH6Tw [6s]
Queued
Building
Completing
Preview: https://<project-name>-<username>-<team-name>.vercel.app [42s]
To deploy to production (<project-name>.vercel.app), run `vercel --prod`
Vercel CLI 29.3.3
> Assigning alias https://<desired-url-subdomain-in-format-described-above>.vercel.app/ to deployment <generated-url-subdomain>.vercel.app
Creating alias
Error: Invalid alias. Please confirm that the alias you provided is a valid hostname. Note: For `vercel.app`, only sub and sub-sub domains are supported.
Error: Process completed with exit code 1.
```

I feel like my alias should be working, even based on the `vercel.app` note in the error.  I navigated to it and saw the code I had previously deployed to that location in earlier builds, so it is definitely a valid URL.

### Steps to Reproduce

My yaml file looks like this:

```
name: Preview
on:
  pull_request:
    branches-ignore:
      - "main"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  deploy:
    name: Deploy to Vercel (preview)
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.set_branch_url.outputs.branch_url }}
    steps:
      - name: Set branch url
        shell: bash
        run: echo "branch_url=https://vesta-poc-git-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-ao-vesta.vercel.app" >> $GITHUB_OUTPUT
        id: set_branch_url
      - name: Set NEXTAUTH_URL
        run: echo "NEXTAUTH_URL=${{ steps.set_branch_url.outputs.branch_url }}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Pull Vercel Environment
        run: yarn vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: yarn vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Branch URL
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_TEAM_ID }} set "$url" ${{ steps.set_branch_url.outputs.branch_url }}
```
