### DISCUSSION TITLE
Extension for Azure DevOps

### DISCUSSION THREAD

**Discussion by allangxg** [vercel/community#2958] [Bug Report]
### Page to Investigate

N/A

### Steps to Reproduce

Configure a Pipeline in Azure DevOps by following the documentation step by step below:

https://vercel.com/docs/concepts/deployments/git/vercel-for-azure-pipelines#

When trying to use the deploy feature for preview when creating a pull request, the error "##[error]vercel alias failed with exit code null. Error: Vercel CLI 30.2.3" is displayed.

![Captura de Tela 2023-06-22 às 12 47 25](https://github.com/vercel/community/assets/14918155/cbefe1e2-4048-413b-b590-148ac4a27c92)

**Comment by amyegan** [comment]
Sorry you're running into this error, @allangxg. Can you share the `vercel-pipeline.yml` to help us reproduce the problem? If you prefer to keep it private, you can open a case at https://vercel.com/help#issues

**Reply by allangxg** [reply]
Hi @amyegan, follow the contents of the file.

```
trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
- task: vercel-deployment-task@1
  name: 'Deploy'
  inputs:
    condition: or(eq(variables.isMain, true), eq(variables['Build.Reason'], 'PullRequest'))
    vercelProjectId: '<PROJECT ID>'
    vercelOrgId: '<TEAM ID>'
    vercelToken: $(VERCEL_TOKEN)
    production: $(isMain)
- task: vercel-azdo-pr-comment-task@1
  inputs:
    azureToken: $(AZURE_TOKEN)
    deploymentTaskMessage: $(Deploy.deploymentTaskMessage)
```
