### DISCUSSION TITLE
Expected — Waiting for status to be reported

### DISCUSSION THREAD

**Discussion by cryptoquick** [vercel/community#3006] [Bug Report]
### Page to Investigate

private git repo

### Steps to Reproduce

We keep having this issue pop up, has anyone else seen this? Is there any way to fix?
![Screenshot from 2023-06-26 10-32-16](https://github.com/vercel/community/assets/285690/f56be2cc-4dc4-4f51-9995-f07efe28b606)

It never resolves, we see this across all PRs.

**Comment by cryptoquick** [comment]
To clarify, the issue is that in the build step, it's waiting for the status to be reported, and this never resolves.

Not sure if this is helpful, but here's what we're using in our Action:

```yaml
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      - name: Purge CloudFlare
        run: 'curl -X POST "https://api.cloudflare.com/client/v4/zones/$CF_ZONE_ID/purge_cache" -H "Authorization: Bearer $CF_API_KEY" -H "Content-Type: application/json" --data "{\"purge_everything\":true}"'
```
