### DISCUSSION TITLE
Cron jobs do not appear in cron jobs list in dashboard

### DISCUSSION THREAD

**Discussion by Archiolidius** [vercel/community#3037] [Help] [answered]
### Summary

I set up cron jobs in vercel.json and redeployed app, but they do not appear in the dashboard's list of cron jobs.

### Steps to Reproduce

I set up cron jobs in vercel.json and redeployed app, but they are not appearing in the dashboard's list of cron jobs.

I also tried to deploy the new project using https://github.com/vercel/examples/tree/main/solutions/cron and it still not working

<img width="1487" alt="image" src="https://github.com/vercel/community/assets/1984487/c85fa2a5-774a-4248-b318-b8c3a7030446">

I tried to create a support ticket (I have a team with the pro plan) but it says that "Hobby plan support has moved to our GitHub" =(

`{
  "crons": [
    {
      "path": "/api/chat/generateChatInsights?interval=1",
      "schedule": "0 * * * *"
    },
    {
      "path": "/api/chat/generateChatInsights?interval=4",
      "schedule": "0 */4 * * *"
    }
  ]
}`

**Comment by ozansozuozgit** [comment]
I have the same issue. I tried using the pages/api/cron and the app directory. 

I had no issues before, it was working as intended.

**Reply by Archiolidius** [reply]
Never mind, I have just used GitHub Actions for cron jobs, which seems more reliable.

For anyone who wishes to do the same, here is an example code of a workflow:

```
name: Trigger URL

on:
  schedule:
    - cron:  '0 * * * *'  # This will run every hour

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Curl request
      run: curl -X GET 'http://your-url.com/api/route?interval=1'
```
