### DISCUSSION TITLE
vercel-azure-devops-extension || How to enable cache for npm package installation

### DISCUSSION THREAD

**Discussion by SomnathKadam** [vercel/community#3118] [Help]
### Summary

Hi team,

Can please guide how to add cache for npm package installation in **vercel-azure-devops-extension**, because for each commit push for master below command take more than 2 minute.

```
 - task: Npm@1
    displayName: "Install Dependencies"
    inputs:
      command: "custom"
      customCommand: "install --production"
      workingDir: ""
```

### Steps to Reproduce

1. Push some test commit to master branch
2. It started "Deploying to Vercel" job on azure pipeline
3. And add above task in azure pipeline
