### DISCUSSION TITLE
Request to login from CLI when aliasing a preview url from github actions/workflow

### DISCUSSION THREAD

**Discussion by 0xemc** [vercel/community#3189] [Help] [answered]
### Summary

Hi there,

I have replicated the github action at https://vercel.com/guides/how-to-alias-a-preview-deployment-using-the-cli and am running in to an issue where the vercel cli is asking to re-authenticate when attempting the alias step

> Assigning alias ---.vercel.app to deployment ---.vercel.app
Creating alias
> You must re-authenticate to use mcoll92 scope.

My github secrets are within a specific environment (that I have selected in the action) and the yaml file looks as follows:

```yaml
# See: https://vercel.com/guides/how-to-alias-a-preview-deployment-using-the-cli
name: Deploy API
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy_preview:
    runs-on: ubuntu-latest
    environment: *****
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set short commit hash to environment variable
        run: echo "SHORT_COMMIT_HASH=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" prefix-${{ env.SHORT_COMMIT_HASH }}-suffix.vercel.app
```

Am I using the wrong token and why is this only an issue when aliasing?

### Steps to Reproduce

1. Copy paste the above workflow
2. Add VERCEL_ORG_ID, VERCEL_PROJECT_ID & VERCEL_TOKEN github secrets to a specific environment
3. Target that environment in the workflow
4. Create a PR
