### DISCUSSION TITLE
dev deployment automatically updating to main deployment

### DISCUSSION THREAD

**Discussion by ddgiter** [vercel/community#3190] [Help] [answered]
### Summary

here is the problem. for some reasons that we can't find out what exactly that is, whenever we update the main deployment of our front. our dev deployment is also updated to that version. but we need it to stay on the version we want it to be. did anyone else have the same problem here? is there anyway we can recognize where the problem is and how to fix it? 
we think the problem is probably from the CLI or maybe our CI/CD configurations on the pipeline

### Steps to Reproduce

this is our CI configs:
```
stages:
  - deploy

deploy prod:
  image: node:16
  stage: deploy
  before_script:
    - npm i -g vercel
    - mkdir .vercel && cp $VERCEL_FILE .vercel/project.json
  script:
    - vercel --token $VERCEL_TOKEN  --prod
  tags:
    - docker
  when: manual
  environment:
    name: prod

deploy dev:
  image: node:16
  stage: deploy
  before_script:
    - npm i -g vercel
    - mkdir .vercel && cp $VERCEL_FILE .vercel/project.json
  script:
    - vercel --token $VERCEL_TOKEN
    - vercel --token $VERCEL_TOKEN alias set https://example-client-dd-deploy.vercel.app/ <example.com>

  tags:
    - docker
  when: manual
  environment:
    name: dev
```
