### DISCUSSION TITLE
Github Actions build error: Could not retrieve Project Settings

### DISCUSSION THREAD

**Discussion by mariliacamara** [vercel/community#3260] [Help] [answered]
### Summary

Hi. I suddenly can't built my project using Github Actions. 
I've checked all the secrets and tested the same workflow in another project that worked fine.
Does anyone know how this can be fixed?

PS: Neither preview or production workflows work.

```bash
Run vercel pull --yes --environment=preview --token=***
  vercel pull --yes --environment=preview --token=***
  shell: /usr/bin/bash -e {0}
  env:
    VERCEL_ORG_ID: ***
    VERCEL_PROJECT_ID: ***
Vercel CLI [3](joburl3#step:4:3)1.0.3
Retrieving project…
Error: Could not retrieve Project Settings. To link your Project, remove the `.vercel` directory and deploy again.
Learn More: https://vercel.link/cannot-load-project-settings
Error: Process completed with exit code 1.
```

### Steps to Reproduce

```yml
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
```
