### DISCUSSION TITLE
Domain setup while using selfhosted-Gitlab

### DISCUSSION THREAD

**Discussion by gijsjager** [vercel/community#3752] [Help]
### Summary

I am using a selfhosted-Gitlab env and deploy the production builds with the Gitlab pipeline:
```
deploy_production:
  stage: deploy
  only:
    - master
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
```

But I want to have a separate domain for our acceptation / preview branches. 

How can I setup the domains to connect them to the correct environment with a selfhosted Gitlab? 

### Steps to Reproduce

- Have a selfhosted Gitlab env
- Deploy to a env
- Try to connect a domain without setting up a GIT-account
