### DISCUSSION TITLE
[UX/UI] vercel.com/ai "Built In Adapters" Card SVGs are not visible in Dark Mode

### DISCUSSION THREAD

**Discussion by David-Lazaro-Fernandez** [vercel/community#3923] [Bug Report]
### Page to Investigate

https://vercel.com/ai

## Hi team 👋  
I was taking a look at the [vercel.com/ai](https://vercel.com/ai) page and found that 2 of the logos that are in the **_Built-in Adapters_ Card** are not visible in dark mode 👀 

I visited the page in the next browsers: _Google Chrome and Microsoft Edge_ 

This is how the card looks on **Light Mode** ⚪  

![image](https://github.com/vercel/community/assets/57787993/a70a037b-74ae-4525-8643-6df779365cc2)

![image](https://github.com/vercel/community/assets/57787993/cf7d5b12-5e68-4b0b-8e81-92df8eacffb5)

And this is how the card looks on **Dark Mode** ⚫

![image](https://github.com/vercel/community/assets/57787993/13c40f2e-2746-4b4c-a8bb-5ccfe222cc1e)

![image](https://github.com/vercel/community/assets/57787993/92df821c-b930-4c19-a5ba-ba749361ed26)

It's really difficult to identify the logos in dark mode.

## Possible solution 💯 

I inspected the elements of the card and found that the tailwind class for the SVGs are configured to be: 
```css
.tailwind :is(.dark-theme .dark\:text-white) {
    color: var(--ds-background-100);
}
```

Changing it to: 

```css
.tailwind :is(.dark-theme .dark\:text-white) {
    color: var(--ds-gray-1000);
}
```

Fixes the problem and doesn't affect the page at all ^^!

![image](https://github.com/vercel/community/assets/57787993/91227a47-9e94-4256-91b1-3d69aa990499)

![image](https://github.com/vercel/community/assets/57787993/d204d8dc-255e-46e7-9054-d4fb5a4cc2ad)
