### DISCUSSION TITLE
Deploy to Vercel with Bun runtime and private dependencies.

### DISCUSSION THREAD

**Discussion by wrux** [vercel/community#4157] [Help] [answered]
### Summary

I have a package published on the Github package registry. I've successfully installed the package with Bun locally, however I cannot find any documentation on how to configure private packages when deploying on Vercel. 

### Steps to Reproduce

Here's my package: `@wrux/sanity-analytics-dashboard-widgets`

Here's the contents of my `bunfig.toml` file in the project:
```toml
[install]
registry = "https://registry.npmjs.org"

[install.scopes]
"@wrux" = { token = "$GITHUB_TOKEN", url = "https://npm.pkg.github.com/" }
```

In other projects using the npm runtime, I normally just add the `.npmrc` configuration in an `NPM_RC` environment variable in Vercel. I assume I'll have to do something similar to get this setup in Bun, but I'm unsure how to get this setup.
