### DISCUSSION TITLE
Runtime env not loaded in Nextjs 13 (App Router) deployed to GKE with docker build

### DISCUSSION THREAD

**Discussion by kangbojk** [vercel/community#4166] [Help]
### Summary

I want to deploy a nextjs 13 application to GKE.

The app use auth0 so I need to provide auth0 related env.

```
AUTH0_SECRET=abc123
AUTH0_BASE_URL=http://localhost:3000
AUTH0_ISSUER_BASE_URL=https://abc123.us.auth0.com
AUTH0_CLIENT_ID=abc123
AUTH0_CLIENT_SECRET=abc123
```

After the image got built, it'll run in GKE. Runtime envs are set with k8s config map, so it'll map envs into a .env file inside container.

But the runtime envs never got loaded, only the built time envs were loaded.

### Steps to Reproduce

Build nextjs13 app with Dockerfile, use image stored in gcr with GKE yaml.
Runtime envs are still same as built time envs, no new envs got loaded. (I provided the dummy envs in runtime so if the runtime env got loaded nextjs app should crash and throw error in frontend)

Files provide below with necessary information. Please let me know if you have any suggestions about fixing this runtime env not loaded in GKE issue, thank you!

Dockerfile
```

FROM node:12.16.1-alpine

WORKDIR /usr/src/app/

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
```

Nextjs13App.yaml

```
---
apiVersion: v1
kind: ConfigMap
name: your-configmap
  
data:
  .env: |
    AUTH0_SECRET=1
    AUTH0_BASE_URL=2
    AUTH0_ISSUER_BASE_URL=3
    AUTH0_CLIENT_ID=4
    AUTH0_CLIENT_SECRET=4
    AUTH0_AUDIENCE=4
    OPTIMUS_API_URL=https://stackoverflow.com/
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=12
---

apiVersion: apps/v1
kind: Deployment
name: your-app
spec:
  revisionHistoryLimit: 4
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  
    spec:
      containers:
        - name: your-container
          image: gcr.io/your-image
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
          volumeMounts:
            - name: your-configmap
              mountPath: /usr/src/app/.env
              subPath: .env
              readOnly: true
      
      volumes:
        - name: your-configmap
          configMap:
            name: your-configmap
```

next.config.js
```

const nextConfig = {
env: {
    NEXT_PUBLIC_GOOGLE_MAPS_API_KEY:
      process.env.GOOGLE_MAPS_API_KEY ||
      "realkey",
    AUTH0_SECRET:
      process.env.AUTH0_SECRET ||
      "realkey",
    AUTH0_BASE_URL:
      process.env.AUTH0_BASE_URL || "realkey",
    AUTH0_ISSUER_BASE_URL:
      process.env.AUTH0_ISSUER_BASE_URL ||
      "realkey",
    AUTH0_CLIENT_ID:
      process.env.AUTH0_CLIENT_ID || "realkey",
    AUTH0_CLIENT_SECRET:
      process.env.AUTH0_CLIENT_SECRET ||
      "realkey",
    AUTH0_AUDIENCE:
      process.env.AUTH0_AUDIENCE || "realkey",
  }

};

```
verified .env exists in container

<img width="633" alt="Screen Shot 2023-09-20 at 10 59 39 AM" src="https://github.com/vercel/community/assets/11307216/464fac58-f731-4566-bdb7-fdb8d3f75cd0">
