### DISCUSSION TITLE
GitHub Actions workflow with "deployment_status" trigger does not run

### DISCUSSION THREAD

**Discussion by mikenikles** [vercel/community#428] [Show & Tell]
Hi,

I have the following GitHub Actions workflow:

```yaml
on: deployment_status

jobs:
  test_lighthouse:
    name: Test Lighthouse
    if: github.event.deployment_status.state == "success"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit Vercel preview URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
          budgetPath: ./services/website/.config/lighthouse/budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
```

I can see the `target_url` when I use `curl` to fetch from the API directly, but for some reason the workflow does not get triggered after Vercel completes the preview deployment.

I'm experimenting with it in https://github.com/mikenikles/www-mikenikles-com/pull/161. Does anyone see what I'm missing?

Thanks,

Mike

**Comment by bartoszgolebiowski** [comment]
I am struggling with the same issue,
https://github.com/bartoszgolebiowski/next-js-prisma.

```yml
name: ci
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on: [deployment_status]
jobs:
  e2e:
    # only runs this job on successful deploy
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v1
      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
```

Preview deploy which succeeds does not trigger this workflow.

**Reply by Fedeorlandau** [reply]
Hi @bartoszgolebiowski  did you find a workaround for this? Cheers

**Reply by bscaspar** [reply]
@bartoszgolebiowski I am able to run this successfully with the following job:
```yml
name: ci
on:
  [deployment_status]
jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
```

The only differences I can spot between your and my job is that I use `actions/checkout@v2`.
