### DISCUSSION TITLE
Can you associate builds with github commits when using the CLI to deploy?

### DISCUSSION THREAD

**Discussion by RayBB** [vercel/community#430] [Help] [answered]
I currently deploy to staging when merging to main and then deploy to prod when tagging a release in GitHub.

To deploy on tag release I use GitHub actions to run `npx vercel --token ${VERCEL_TOKEN}`.

One annoying things about deploying this way is that the builds are no longer associated with git commits (like they are for the deploys to staging).

I have tried setting the following environment variables.
```
          VERCEL_GIT_PROVIDER:
          VERCEL_GIT_REPO_SLUG:
          VERCEL_GIT_REPO_OWNER:
          VERCEL_GIT_REPO_ID: # comes from https://stackoverflow.com/questions/13902593/how-does-one-find-out-ones-own-repo-id
          VERCEL_GIT_COMMIT_REF:
          VERCEL_GIT_COMMIT_SHA: 
          VERCEL_GIT_COMMIT_MESSAGE: 
          VERCEL_GIT_COMMIT_AUTHOR_LOGIN: 
          VERCEL_GIT_COMMIT_AUTHOR_NAME:
```
I've also tried prepending `NEXT_PUBLIC_` next.js.

However, in any case vercel doesn't seem to show association in the GUI. 

Related docs about linking github and vercel https://vercel.com/docs/concepts/git
This doc describes how these variables are exposed but doesn't say anything about setting them:
https://vercel.com/docs/concepts/git/vercel-for-github#configuring-vercel-for-github
