### DISCUSSION TITLE
Wrong default URL for preview deployments

### DISCUSSION THREAD

**Discussion by estyrke** [vercel/community#4323] [Help]
### Summary

We are using Vercel to deploy a static react app, it has one production deployment at app.example.com tied to the `app` branch and one preview deployment at dev.app.example.com tied to the `app-dev` branch. Now I am trying to set up a GitHub Action to run Playwright tests against the preview deployment using the `deployment_status` workflow trigger. This almost works, but due to CORS settings in our API server, the requests must come from *.example.com, but the webhook that Vercel sends to GitHub Actions has `github.event.deployment_status.target_url` set to the "Unique deployment link" (project-jhTtu567.vercel.app) instead of our custom domain URL (dev.app.example.com), which prevents the tests from running. Looking at the deployment status page shows both these URLs  under "Domains" (and also the branch-specific URL). I also noticed that using "Copy URL" from the deployment page gives the same ("Unique") URL, but the "Share" action correctly shows the custom URL.

Is there any way for us to solve this without hard-coding the custom domains in the workflow definition?

### Steps to Reproduce

1. Set up a Vercel project with a custom domain assigned to a (preview) branch.
2. Set up a GitHub action triggered by `deployment_status` on the preview branch:

```yaml
name: Playwright Tests
on:
  deployment_status:
jobs:
  set_env:
    runs-on: ubuntu-latest
    steps:
      - id: set
        run: |
          echo Event: ${{ github.event_name }}
          echo Target URL: ${{ github.event.deployment_status.target_url }}
          echo State: ${{ github.event.deployment_status.state }}
```

3. Trigger a deployment
4. Wait for the deployment to finish and the workflow to run.
5. Expected `Target URL` is the custom domain set for the branch
6. Actual `Target URL` is the "unique deployment URL" of the deployment
