### DISCUSSION TITLE
Challenges with Sequential GitLab CI/CD Pipeline and Vercel Deployment

### DISCUSSION THREAD

**Discussion by mustafadalga** [vercel/community#4780] [Help]
### Summary

Hello,

I'm reaching out for help with an issue in my GitLab CI/CD pipeline when integrating with Vercel deployments. My project is a Next.js application, and I've configured GitLab CI/CD to run end-to-end tests followed by conditional deployments to Vercel.

Despite my gitlab-ci.yml configuration, which specifies test stages before deployment stages, Vercel deployments are triggered as soon as code is pushed, without waiting for the test results. This is the core of my .gitlab-ci.yml:

```
stages:
  - test
  - deploy

test_e2e:
  stage: test
  script:
    - npm ci
    - npx install playwright
    - npm run test:e2e

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

```

The CI/CD variables, including VERCEL_TOKEN, are configured correctly in GitLab. However, Vercel seems to be treating the deployment as an "external" stage and proceeding with it even if the test_e2e stage fails.

I have attached a screenshot of the GitLab pipeline.

<img src="https://github-production-user-asset-6210df.s3.amazonaws.com/25087769/281537620-3008e07f-26ea-4a91-885f-2fcb74792b44.png"/>

I'm looking to have a pipeline where:

The end-to-end tests run first.
If tests pass, then proceed with the Vercel deployment.
Vercel deployment should not occur if tests fail.
Any advice on how to ensure that Vercel deployments are strictly sequential following the GitLab pipeline stages would be invaluable.

Thank you for your assistance!

### Steps to Reproduce

**Actual Behavior:**
The deployment to Vercel is triggered regardless of the test stage results, with both Vercel's "external" deployment stage and the GitLab test stage running concurrently.

**Refined Steps to Reproduce:**

1. **Configure GitLab CI/CD**: Set up `.gitlab-ci.yml` with distinct `test` and `deploy` stages, intending for Vercel deployment to depend on test success.
2. **Trigger Pipeline**: Push changes to the repository, initiating the CI/CD process.
3. **Witness Incorrect Pipeline Execution**: The Vercel deployment begins immediately as an "external" stage, without waiting for the `test` stage to pass.
4. **Inspect Pipeline Stages**: Note that the "external" Vercel deployment doesn't respect the sequential stage execution as configured in `.gitlab-ci.yml`.

**Expected vs. Actual Behavior**:
- *Expected*: Vercel deployment post-tests.
- *Actual*: Concurrent Vercel deployment and testing.
