### DISCUSSION TITLE
Using GitHub Actions CI/CD with Vercel Deployment. Receiving Error: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free")

### DISCUSSION THREAD

**Discussion by xmliszt** [vercel/community#4893] [Help] [answered]
### Summary

Hi! Recently when I do deployment using GitHub Actions with Vercel integration, I am receiving 

**Error: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free").**

this error. Though it is self-explanatory that I have exceeded the limits. I want to ask the following questions:

- Where can I find my usage regarding this metrics on Vercel? I can't seem to find it that indicates my usage has exceeded the limit. I hope there is somewhere that I can see the metrics so that I can troubleshoot. 
- "Too many requests" during deployment stage means what? "api-upload-free" seems to suggest that the deployment is trying to upload APIs and it exceeds the request limits? For my app, I only have like 6 APIs built in. I don't know how I can actually exceed this limit though...

### Steps to Reproduce

Here is the log I receive:

```
Vercel CLI 32.5.5
Retrieving project…
Deploying xmliszt/taboo-ai
Uploading [--------------------] (0.0B/9.1MB)
Uploading [=====---------------] (2.3MB/9.1MB)
Uploading [==========----------] (4.5MB/9.1MB)
Uploading [===============-----] (6.8MB/9.1MB)
Error: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free").
Error: An unexpected error occurred!
DeploymentError: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free").
    at uploadList.<computed>.retries (/opt/hostedtoolcache/node/19.9.0/x64/lib/node_modules/vercel/dist/index.js:64401:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Uploading [====================] (9.1MB/9.1MB)
Error: An unexpected error occurred!
DeploymentError: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free").
    at uploadList.<computed>.retries (/opt/hostedtoolcache/node/19.9.0/x64/lib/node_modules/vercel/dist/index.js:64401:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: An unexpected error occurred!
DeploymentError: Too many requests - try again in 7 hours (more than 5000, code: "api-upload-free").
    at uploadList.<computed>.retries (/opt/hostedtoolcache/node/19.9.0/x64/lib/node_modules/vercel/dist/index.js:64401:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

And here is my deployment CICD workflow:

```
name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - 'preview'
  workflow_dispatch:
jobs:
  Unit-Test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Running Jest Tests
        run: npm test
  Deploy-Preview:
    needs: Unit-Test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install Node Dependencies
        run: npm ci
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
```

The error occurs at the "Deploy Project Artifacts to Vercel" stage

And here is a screenshot of my deployment inspection for functions:

![image](https://github.com/vercel/community/assets/44829092/af91c2f8-6ee9-4ed1-8e76-afe55ad52202)
