### DISCUSSION TITLE
E2E test against the Vercel Preview with GitHub Actions stuck on Login Page

### DISCUSSION THREAD

**Discussion by devjiwonchoi** [vercel/community#4944] [Help]
### Question

I've followed the Vercel guide of [How can I run end-to-end tests after my Vercel Preview Deployment?
](https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment)

Everything works fine, but the playwright seems caught on the login page.

```
Test timeout of 30000ms exceeded.

    Error: expect(locator).toHaveTitle(expected)

    Locator: locator(':root')
    Expected string: "Jiwon Choi"
    Received string: "Login – Vercel"
// ...
```

### My workflow yml

```yaml
name: build-and-test

on:
  deployment_status:

jobs:
  e2e-playwright:
    name: e2e-playwright
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Install playwright browsers
        run: pnpm playwright install --with-deps

      - name: Run tests
        run: pnpm test:e2e
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
```

### Example

https://github.com/devjiwonchoi/jiwonchoi.dev/actions/runs/6971545815/job/18971836641#step:7:57

### Steps to Reproduce

Follow the guide [How can I run end-to-end tests after my Vercel Preview Deployment?
](https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment)
