### DISCUSSION TITLE
overwrite variables from Vercel using GitHub Actions

### DISCUSSION THREAD

**Discussion by kendjr** [vercel/community#5113] [Help]
### Summary

We are using GitHub actions to pull the environment variables from Vercel for preview deployments. We would like to override certain environment variables stored in vercel for specific non-production branches. We have set environment variables in GitHub Environments, but they are ignored and only the Vercel environment variables are used. Is there any way use the GitHub Environment Variables?

We can't set the environment variables for specific branches through the Vercel Console because we are using Short Life Feature Branches. Although we have a naming convention, Vercel does not let us use a wildcard "branch name = fe*"

Our GitHub action pulls the Vercel environment variables as per the code below:

```
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - id: deploy
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=company set "$url" ${{ vars.DEV_ALIAS }}
          echo "DEPLOYMENT_URL=$url" >> "$GITHUB_OUTPUT"
```

### Steps to Reproduce

![env](https://github.com/vercel/community/assets/3506293/d7474a3d-bffe-4ca1-bf8e-b4051ac3831c)

**Comment by nkpgardose** [comment]
@kendjr did you find a solution for this one? I need to override certain variables in vercel and use github env secrets. :D

**Reply by kendjr** [reply]
yes, please check this out for preview environments. We have a similar one for the production environment.
```
name: Deploy Preview

#Environment variables are stored in the GitHub repo Environments section. It will prioritize environment variables as follows:
# 1. GitHub "branch" environment variables. (using the first four letters of the branch name to match the GitHub environment)
# 2. GitHub "repository" environment variables
# 3. Vercel environment variables for preview environments. 

#variables set with env: are static and cannot be reset inside of the workflow
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

#if needed, can set it to run manually using GitHub Console using "workflow dispatch", otherwise will run 
#automatically when we push to the specific branches
on:
  workflow_dispatch:
  push:
    branches:
      - 'hh*'

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_env_name.outputs.env_name }}
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME_PREFIX=$(echo ${GITHUB_REF#refs/heads/} | cut -c1-4)" >> $GITHUB_ENV

      - name: Set output
        id: set_env_name
        run: echo "env_name=${{ env.BRANCH_NAME_PREFIX }}" >> $GITHUB_OUTPUT

      - run: echo "The environment is ${{ env.BRANCH_NAME_PREFIX }}"
        
    #this is "build-and-deploy" is the job name and visible on the github actions map
  build-and-deploy:
    needs: set-env
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-env.outputs.env_name }}
      url: ${{ steps.deploy.outputs.DEPLOYMENT_URL }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
    #use name before the run commands so it is easier to read the GitHub Actions log
      - run: pnpm install --frozen-lockfile
      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest
    #this will go to Vercel.com to pull the environment variables
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
    #override the vercel variables with GitHub variables
      - name: Pull the GitHub Environment variables
        run: |
          echo "NEXT_PUBLIC_AWS_COGNITO_POOL_ID=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_POOL_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID=${{ secrets.NEXT_PUBLIC_AWS_COGNITO_CLIENT_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_AWS_IDENTITY_POOL_ID=${{ secrets.NEXT_PUBLIC_AWS_IDENTITY_POOL_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_FACEBOOK_APP_ID=${{ secrets.NEXT_PUBLIC_FACEBOOK_APP_ID }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_GOOGLE_API_KEY=${{ secrets.NEXT_PUBLIC_GOOGLE_API_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_WEATHER_API=${{ secrets.NEXT_PUBLIC_WEATHER_API }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_WEATHER_KEY=${{ secrets.NEXT_PUBLIC_WEATHER_KEY }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_WEATHER_EXCLUDE=${{ secrets.NEXT_PUBLIC_WEATHER_EXCLUDE }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL=${{ secrets.NEXT_PUBLIC_WEATHER_REFRESH_INTERVAL }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_HASH_SALT=${{ secrets.NEXT_PUBLIC_HASH_SALT }}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_BUILD_TIME=$(date -u +"%Y-%m-%d Time: %H:%M:%S")" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_COMMIT_MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_ENV_NAME=${{ needs.set-env.outputs.env_name }}" >> $GITHUB_ENV

 
    #vercel build function builds the application without sending the source to vercel
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - run: echo "Deployment URL is ${{ vars.DEV_ALIAS }}"
      - run: echo "GitHub ref name is ${{ github.ref_name }}"

# the - id: deploy line is used to assign an identifier to a specific step within a job. 
# This identifier (id) allows you to reference outputs from that step in subsequent 
# steps or jobs within the same workflow.

#now we deploy the built app to vercel using the --prebuild option because it is already built
      - id: deploy
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=hamlethub set "$url" ${{ vars.DEV_ALIAS }}
          echo "DEPLOYMENT_URL=$url" >> "$GITHUB_OUTPUT"
```
