### DISCUSSION TITLE
Vercel is removing the <style> tag when serving html page under an assigned domain

### DISCUSSION THREAD

**Discussion by xdamman** [vercel/community#5321] [Bug Report]
### Page to Investigate

https://pages-n9qmqc6z2-citizenspring1.vercel.app/dao.brussels/manifesto

### Steps to Reproduce

When I request the page from the deployment URL, I get the proper HTML page that has two `<style></style>` tags in the body of the html. 

```
curl -i https://pages-n9qmqc6z2-citizenspring1.vercel.app/dao.brussels/manifesto
```

But when I add the host, I get a different version, or rather a trimmed down / over optimized version that only has one `<style></style>` tag (the second one)

```
curl -H "Host: dao.brussels"  https://pages-n9qmqc6z2-citizenspring1.vercel.app/dao.brussels/manifesto
```

The style that defines the background color of the footer is removed (even though the #footer element is there, so no reason for an optimizer such as `purgecss` to remove it)

```css
#footer {
  background-color: color-mix(in srgb, #34348c, black 50%);
}
```

How can I turn that optimization off?
Or how can I make sure that the extra styles are not being removed?

**Comment by xdamman** [comment]
I tried to combine all the css rules within the same `<style>` tag in this new deployment: https://pages-ibezt7sq8-citizenspring1.vercel.app/dao.brussels/manifesto

Same issue. All the custom rules are removed once I add the host in the header. 

`curl -H "Host: dao.brussels" https://pages-ibezt7sq8-citizenspring1.vercel.app/dao.brussels/manifesto`

```css
...
<style>.content.index p { margin-top: 2px; margin-bottom: 2px; } .content .button.primary { background-color: #563087 !important; } .content .button.primary:hover { background-color: #290755 !important; } .content .button.secondary { border-color: #290755 !important; background-color: white !important; color: #290755 !important; } .content a { color: #563087 !important; } .content a:hover { color: #290755 !important; } .content h3 span { font-weight: 900; font-size: 16pt; color: #290755 !important; } #footer { background-color: color-mix(in srgb, #34348c, black 50%); } #footer .icon { filter: invert(1); width: 100%; height: auto; max-width: 64px; } #footer a { color: white; } #footer a:hover { color: color-mix(in srgb, #34348c, white 50%); text-decoration: underline; }

.c0{orphans:2;widows:2;text-align:left}.c1{color:#000000;font-weight:400;text-decoration:none;vertical-align:baseline;font-size:11pt;font-family:&quot;Arial&quot;;font-style:normal}.c9{page-break-after:avoid;orphans:2;widows:2;text-align:center}.c10{color:#000000;font-weight:400;text-decoration:none;vertical-align:baseline;font-size:20pt;font-family:&quot;Arial&quot;;font-style:normal}.c2{orphans:2;widows:2;text-align:left}.c4{text-decoration-skip-ink:none;-webkit-text-decoration-skip:none;color:#0000ee;text-decoration:underline}.c8{background-color:#ffffff;max-width:451.3pt;}.c6{color:inherit;text-decoration:inherit}.c7{}.c3{color:#1155cc}.c5{height:11pt}</style>
...
```

`curl -H "Host: dao.brussels" https://pages-ibezt7sq8-citizenspring1.vercel.app/dao.brussels/manifesto`

```css
...
<style>

.c10{color:#000000;font-weight:400;text-decoration:none;vertical-align:baseline;font-size:20pt;font-family:&quot;Arial&quot;;font-style:normal}.c8{page-break-after:avoid;orphans:2;widows:2;text-align:center}.c0{color:#000000;font-weight:400;text-decoration:none;vertical-align:baseline;font-size:11pt;font-family:&quot;Arial&quot;;font-style:normal}.c2{orphans:2;widows:2;text-align:left}.c9{text-decoration-skip-ink:none;-webkit-text-decoration-skip:none;color:#0000ee;text-decoration:underline}.c7{background-color:#ffffff;max-width:451.3pt;}.c4{}.c6{}.c1{color:inherit;text-decoration:inherit}.c3{color:#1155cc}.c5{height:11pt}</style>
...
```

While some of the rules make sense to remove (e.g. there is no element that match the css selector `.content.index` on that page), there are some rules that do apply (e.g. `.content a`,  `#footer a`, ...).
