### DISCUSSION TITLE
Error: You cannot set your Personal Account as the scope.

### DISCUSSION THREAD

**Discussion by Ilya-Valasiuk** [vercel/community#5400] [Help]
### Summary

Trying to add pull requests preview feature to my project (azure devops repos + vercel).

Here is pipeline:
```
trigger:
  - develop

pool:
  vmImage: ubuntu-latest

variables:
  isTarget: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

steps:
  - task: vercel-deployment-task@1
    name: 'Deploy'
    inputs:
      condition: or(eq(variables.isTarget, true), eq(variables['Build.Reason'], 'PullRequest'))
      vercelProjectId: $(VERCEL_PROJECT_ID)
      vercelOrgId: $(VERCEL_ORG_ID)
      vercelToken: $(VERCEL_TOKEN)
      production: $(isTarget)
  - task: vercel-azdo-pr-comment-task@1
    inputs:
      azureToken: $(AZURE_TOKEN)
      deploymentTaskMessage: $(Deploy.deploymentTaskMessage)
```

And here is error:
```
Starting: Deploy
==============================================================================
Task         : Vercel Deployment Task
Description  : An Azure Pipelines Task Extension for automatically deploying to Vercel
Version      : 1.2.2
Author       : Vercel
Help         : https://github.com/vercel/vercel-azure-devops-extension
==============================================================================
Vercel Project Id specified by both `vercelProjectId` input and `VERCEL_PROJECT_ID` environment variable. Input field `vercelProjectId` will be used.
Vercel Org Id specified by both `vercelOrgId` input and `VERCEL_ORG_ID` environment variable. Input field `vercelOrgId` will be used.
Vercel Token specified by both `vercelToken` input and `VERCEL_TOKEN` environment variable. Input field `vercelToken` will be used.
/usr/local/bin/npm install -g vercel@latest
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
added 1 package, removed 1 package, and changed 245 packages in 16s

16 packages are looking for funding
  run `npm fund` for details
/usr/local/bin/vercel pull --yes --environment=preview --token=***
Vercel CLI 33.0.2
Retrieving project…
> Downloading `preview` Environment Variables for Project PROJECT_NAME
Downloading
Created .vercel/.env.preview.local file  [201ms]

> Downloading project settings
Downloaded project settings to ~/work/1/s/.vercel/project.json [0ms]
/usr/local/bin/vercel deploy --token=*** --cwd=/home/vsts/work/1/s
Vercel CLI 33.0.2
Retrieving project…
Deploying ...
Uploading [--------------------] (0.0B/3.6KB)
Uploading [====================] (3.6KB/3.6KB)
Inspect: https://vercel.com/PROJECT_NAME-projects/PROJECT_NAME-lp-dev/Dg4VAwsLXUMRH2Gt71ho4mnKxnbd [4s]
Preview: https://PROJECT_NAME-lp-epx4e6wuq-PROJECT_NAME-projects.vercel.app/ [4s]
Queued
Building
Completing
To deploy to production (PROJECT_NAME-lp-dev.vercel.app), run `vercel --prod`
/usr/local/bin/vercel alias https://PROJECT_NAME-lp-epx4e6wuq-PROJECT_NAME-projects.vercel.app/ PROJECT_NAME-lp-dev-feature-vercel-preview-test-undefined.vercel.app --token=*** --scope=Wqm9qZIaE20NX2KwInVvqkjf
Vercel CLI 33.0.2
Error: You cannot set your Personal Account as the scope.
##[error]vercel alias failed with exit code 1. Error: Vercel CLI 33.0.2
Error: You cannot set your Personal Account as the scope.

Finishing: Deploy
```

### Steps to Reproduce

Following documentation:
1) https://github.com/vercel/vercel-azure-devops-extension?tab=readme-ov-file#extension-set-up
2) https://vercel.com/docs/deployments/git/vercel-for-azure-pipelines
