### DISCUSSION TITLE
!!! Vercel CLI v33.3.0 BUGY

### DISCUSSION THREAD

**Discussion by brnpimentel** [vercel/community#5612] [Bug Report]
### Page to Investigate

https://vercel.com

### Steps to Reproduce

The `vercel build` command is different from 33.2.0, and it's not generating the `node_modules` folders in output/functions. A lot of files are missing in output folder! Caution! 

When deploying with Vercel using `vercel deploy --prebuilt` getting error:
![Screen 2024-01-25 às 22 43 33](https://github.com/vercel/community/assets/6596579/663fa7fb-f22e-4a66-85af-8cc896a15a62)

Downgrade to 33.2.0 until fix!

**Comment by TooTallNate** [comment]
The files are intentionally "missing" from the output functions directories (actually, they are now references in the `.vc-config.json` file within the `*.func` directories). Is it possible that you are using a different version of Vercel CLI when doing the `vc deploy --prebuilt` command? If not, could you share an example repository where the issue occurs?

**Reply by mkultracreative** [reply]
I get this regardless of using the CLI. JUST using Vercels native tool which seems like the very point of vercel’s function. To handle these missing end points

**Comment by brnpimentel** [comment]
That’s it! The versions was different! Thanks!

**Reply by brnpimentel** [reply]
Sorry @TooTallNate, even with the same version i'm getting the error too.

Node 18.19.0
Vercel Cli 33.3.0

Building and trying to deploy with the same version.

Running in different jobs (github actions):
`npx vercel build --prod`
`npx vercel deploy --prebuilt --prod`

The build is fine, but the deployment is giving this:
```
npm WARN exec The following package was not found and will be installed: vercel@33.3.0
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. 
npm WARN deprecated uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Vercel CLI 33.3.0
Retrieving project…
Deploying www3
Error: ENOENT: no such file or directory, lstat '/home/runner/work/v3-www/v3-www/node_modules/styled-jsx/index.js'
Error: Process completed with exit code 1.
```

I'm using github actions to deploy to vercel, in different files. This is the build workflow:

```
   steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout files
        uses: actions/checkout@v3

      - name: Install node packages
        run: |
          npm ci

      - name: Pull Vercel Env Vars
        run: |
          npx vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Buiid vercel
        run: |
          npx vercel build --token=${{ env.VERCEL_TOKEN }} --prod
      ...
```


And then in another job:
```
   steps:
     - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      ....

      - name: Deploy Project Artifacts to Vercel
        run: |
          npx vercel deploy --prebuilt --token=${{ env.VERCEL_TOKEN }} --prod
```
