### DISCUSSION TITLE
GitHub integration permatually marked `deployment_status.state` as `success`

### DISCUSSION THREAD

**Discussion by mwskwong** [vercel/community#6056] [Bug Report]
### Page to Investigate

https://github.com/mwskwong/resume/actions/runs/8197895946

### Steps to Reproduce

I have set up the following GitHub Action

```yml
name: Unlighthouse
on: deployment_status

jobs:
  unlighthouse:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @unlighthouse/cli puppeteer
      - run: npm list -g @unlighthouse/cli
      - run: unlighthouse-ci --site ${{ github.event.deployment_status.environment_url }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          path: ./.unlighthouse
```

A few days ago, I noticed this pipeline is getting triggered even when the site is still deploying. The result of the Lighthouse run, which can be downloaded as an artifact and served via `npx serve`, suggests that Lighthouse is run on the "Deployment in progress" page.

It seems that the issue was introduced recently since the same pipeline run 2 days ago was correctly skipped when the build failed. https://github.com/mwskwong/resume/actions/runs/8166516178
