### DISCUSSION TITLE
Vercel CLI Use branch name in PR deployments

### DISCUSSION THREAD

**Discussion by nickhow83** [vercel/community#6114] [Help]
### Summary

I've been searching around, but have exhausted my Googling skills.  I have up until recently been using the Vercel connection to Github and it's been working really well.  

However, we have got to a point where we will need to run some additional steps and have migrated over to using Github actions to deploy to Vercel.

Everything is working great, apart from one thing that I cannot figure out.  The action builds and deploys for PRs but only assigns a url with a structure of `<project-name>-<unique-hash>-<scope-slug>.vercel.app`.  What I would like to do is deploy PR to the following structure, as-per what is done with the connection: `<project-name>-<branch-name>-<scope-slug>.vercel.app`

I'm probably missing something simple, but I'm out of ideas and could do with some help.

### Steps to Reproduce

Create a github action with the following:

```yaml
name: Vercel PR Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --git-branch=${{steps.extract_branch.outputs.branch}} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

```

Run the action by creating a new PR.

This is as far as I've got.  It still deploys using the `unique-hash`.  Any thoughts are appreciated.
