### DISCUSSION TITLE
Testing with cypress against preview environment url

### DISCUSSION THREAD

**Discussion by jiwidi** [vercel/community#6204] [Help]
### Summary

Hi!

I have a github action where i try to test against the just deployed preview environment following the example at official docs
https://vercel.com/guides/how-can-i-run-end-to-end-tests-after-my-vercel-preview-deployment but is not working.

```
name: Cypress E2E Tests

on:
  deployment_status:

jobs:
  run-e2e-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npx cypress run --env BASE_URL=${{ github.event.deployment_status.environment_url }}

```

The action will run but cypress will not have acess to the preview url and get
```
{BASE_URL}
The response we received from your web server was:
  > [40](https://github.com/XXX/actions/runs/8376881413/job/22937593175?pr=18#step:6:41)1: Unauthorized
  ```
  
  How can i set up authentification so cypress can connect to it?

Same happens when using the oficial cypress testing action:

```
name: Cypress E2E Tests

on:
  deployment_status:

jobs:
  run-e2e-tests:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress 🌲
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}

```

### Steps to Reproduce

Run github action
