### DISCUSSION TITLE
Is the VAAS  project against the Vercel ToS

### DISCUSSION THREAD

**Discussion by versecafe** [vercel/community#6614] [Help]
### Summary

@amyegan @leerob The vercel terms of service forbid scrapers as never fair use, and I'm not sure if VAAS would fall under this as it's essentially a a UI wrapper around the vercel analytics API to allow users to conveniently export their analytics data without needing to manually craft the API requests URI encode them and then process and format the data, but it is arguably a scraper and if it's against the ToS I can take it down immediately

<img width="1410" alt="image" src="https://github.com/vercel/community/assets/147033096/de128331-38fd-4fb1-9fee-62a4a4ac5c99">

example return
```yaml
dataset:
  - key: 2024-03-25
    total: 93
    devices: 31
  - key: 2024-03-26
    total: 121
    devices: 47
  - key: 2024-03-27
    total: 42
    devices: 19
  - key: 2024-03-28
    total: 123
    devices: 57
```

github URL: https://github.com/versecafe/vaas
prod URL: https://vaas-brown.vercel.app

### Example

https://github.com/versecafe/vaas

### Steps to Reproduce

* section irellivant
