### DISCUSSION TITLE
Serverless function crashes in deploying express app built with typescript

### DISCUSSION THREAD

**Discussion by adityanithariya** [vercel/community#6752] [Help]
### Summary

For deploying, followed the step of building and pushing the build folder to repo using github action to another branch, I have deployed that specific branch, but it gives error on starting the server, which crashes the serverless function
Error:
```
Cannot find module '/var/task/dist/controller/auth.controller'
Require stack:
- /var/task/app.js
Did you forget to add it to "dependencies" in `package.json`?
Node.js process exited with exit status: 1. The logs above can help with debugging the issue.
INIT_REPORT Init Duration: 165.56 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Unknown application error occurred
```
Able to run it locally on deployment branch using `node app.js`, but crashes on deployment.
Feel free to ask follow up question to resolve the issue.
Thanks in Advance!

### Example

https://daystream-server.vercel.app/

### Steps to Reproduce

Create a node.js and typescript based project, add below github actions to build and deploy this project to another branch of same repo:
```yaml
name: Build and Prepare for Vercel Deployment

on:
    push:
        branches: [release]

jobs:
    build-and-clean:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js 18.17.0
              uses: actions/setup-node@v3
              with:
                  node-version: 18.17.0

            - name: Install dependencies
              run: yarn server:install

            - name: Build project
              run: yarn server:build

            - name: Clean up compiled TypeScript files
              run: |
                  cd server
                  find . -name "*.ts" -type f -delete
                  sed -i 's/dist\///g' package.json

            - name: Copy build artifacts to root directory
              run: |
                  cd server
                  mv dist/* .

            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: server/deploy
                  FOLDER: server
                  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
```

Deploy this branch in vercel with below vercel.json
```json
{
  "version": 2,
  "builds": [
    {
      "src": "app.js",
      "use": "@vercel/node"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "app.js"
    }
  ]
}
```
