### DISCUSSION TITLE
Website work in Localhost but in Vercel show 404: NOT_FOUND

### DISCUSSION THREAD

**Discussion by can-oktay404** [vercel/community#7325] [Help]
### Summary

My HTML
```HTML
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="mizu.its.moe | mizu.is-a.dev">
  <meta property="og:description" content="mizu.its.moe | mizu.is-a.dev">
  <meta property="og:title" content="Mizu🍊">
  <meta property="og:image" content="">
  <meta property="og:type" content="website">
  <link rel="canonical" href="https://karbone..github.io/">
  <meta property="og:site_name" content="@karbone.">
  <meta name="keywords" content="karbone.,mizu, mizumiyagawa, miyagawa, miyagawa mizu">
  <meta property="og:image" content="https://cdn.discordapp.com/attachments/953841823338618900/1193970050365919292/tumblr_5d43d3aee5d6a0f535c75ebd4654a423_0a23ad45_1280.gif">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="author" content="karbone.">
  <meta name="view-transition" content="same-origin">
  <title>Karbone</title>

  <style>
    /* Styles généraux */
    :root {
      --primary-color-top: #414141;
      --primary-color-bottom: #131113;
      --text-color: black;
      --box-shadow-color: rgba(0, 0, 0, 0.1);
      --welcome-font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }

    body {
      margin: 0;
      background: linear-gradient(var(--primary-color-top), var(--primary-color-bottom));
      color: white;
      font-family: Arial, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
    }

    .overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.9);
      display: flex;
      justify-content: center;
      align-items: center;
      opacity: 1;
      transition: opacity 0.5s ease-in-out;
      z-index: 1000;
    }

    .overlay.hide {
      opacity: 0;
      pointer-events: none;
    }

    .welcome-message {
      font-family: var(--welcome-font-family);
      font-size: 72px;
      color: #ffffff;
      text-align: center;
      animation: animateWelcome 2s ease-in-out forwards;
    }

    @keyframes animateWelcome {
      0% {
        transform: scale(0.7);
        opacity: 0;
      }
      50% {
        transform: scale(1.1);
      }
      100% {
        transform: scale(1);
        opacity: 1;
      }
    }


    /* Styles pour le lecteur de musique */
    .music-player {
      position: relative;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 20px;
      background: rgba(0, 0, 0, 0.5);
      border-radius: 10px;
      box-shadow: 0 4px 8px var(--box-shadow-color);
      z-index: 1; /* Mettre au-dessus de l'overlay */
    }

    .play-pause-button {
      width: 50px;
      height: 50px;
      border: none;
      border-radius: 50%;
      background-color: #414141;
      color: white;
      cursor: pointer;
      font-size: 18px;
      margin-bottom: 10px;
      transition: background-color 0.3s, transform 0.3s;
    }

    .play-pause-button:hover {
      background-color: #5a5a5a;
      transform: scale(1.1);
    }

    .time-remaining {
      font-size: 14px;
      margin-bottom: 10px;
    }

    .controls {
      display: flex;
      align-items: center;
    }

    .seek-bar {
      width: 200px;
      height: 6px;
      background-color: #666;
      border-radius: 3px;
      margin: 0 10px;
      position: relative;
      cursor: pointer;
    }

    .seek-bar-fill {
      height: 100%;
      background-color: #fff;
      border-radius: 3px;
    }

    .seek-bar-thumb {
      width: 12px;
      height: 12px;
      background-color: #fff;
      border-radius: 50%;
      position: absolute;
      top: 50%;
      transform: translateY(-50%);
      cursor: pointer;
    }

    .controls button {
      background-color: #414141;
      color: white;
      border: none;
      border-radius: 50%;
      width: 30px;
      height: 30px;
      font-size: 14px;
      cursor: pointer;
      margin: 0 5px;
      transition: background-color 0.3s, transform 0.3s;
    }

    .controls button:hover {
      background-color: #5a5a5a;
      transform: scale(1.1);
    }


    
                :root {
                  --primary-color-top: #414141;
                  --primary-color-bottom: #131113;
                  --text-color: black;
                  --box-shadow-color: rgba(0, 0, 0, 0.1);
                }
        
                body {
                  margin: 0;
                  background: linear-gradient(var(--primary-color-top), var(--primary-color-bottom));
                  color: white;
                  font-family: Arial, sans-serif;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
                }
        
                .music-player {
                  position: fixed;
                  top: 20px;
                  right: 20px;
                  display: flex;
                  flex-direction: column;
                  align-items: center;
                  padding: 20px;
                  background: rgba(0, 0, 0, 0.5);
                  border-radius: 10px;
                  box-shadow: 0 4px 8px var(--box-shadow-color);
                }
        
                .play-pause-button {
                  width: 50px;
                  height: 50px;
                  border: none;
                  border-radius: 50%;
                  background-color: #414141;
                  color: white;
                  cursor: pointer;
                  font-size: 18px;
                  margin-bottom: 10px;
                  transition: background-color 0.3s, transform 0.3s;
                }
        
                .play-pause-button:hover {
                  background-color: #5a5a5a;
                  transform: scale(1.1);
                }
        
                .time-remaining {
                  font-size: 14px;
                  margin-bottom: 10px;
                }
        
                .controls {
                  display: flex;
                  align-items: center;
                }
        
                .seek-bar {
                  width: 200px;
                  height: 6px;
                  background-color: #666;
                  border-radius: 3px;
                  margin: 0 10px;
                  position: relative;
                  cursor: pointer;
                }
        
                .seek-bar-fill {
                  height: 100%;
                  background-color: #fff;
                  border-radius: 3px;
                }
        
                .seek-bar-thumb {
                  width: 12px;
                  height: 12px;
                  background-color: #fff;
                  border-radius: 50%;
                  position: absolute;
                  top: 50%;
                  transform: translateY(-50%);
                  cursor: pointer;
                }
        
                .controls button {
                  background-color: #414141;
                  color: white;
                  border: none;
                  border-radius: 50%;
                  width: 30px;
                  height: 30px;
                  font-size: 14px;
                  cursor: pointer;
                  margin: 0 5px;
                  transition: background-color 0.3s, transform 0.3s;
                }
        
                .controls button:hover {
                  background-color: #5a5a5a;
                  transform: scale(1.1);
                }
  </style>
</head>
<body>
  <div class="overlay" id="overlay">
    <div class="welcome-message" id="welcome-message">
      Bienvenue sur notre site !
    </div>
  </div>
  <div class="content" id="content">
    <div class="music-player">
      <button class="play-pause-button" onclick="togglePlayPause()">►</button>
      <div class="time-remaining" id="time-remaining">
        Temps restant : 00:00
      </div>
      <div class="controls">
        <button onclick="seekBackward()">-</button>
        <div class="seek-bar" id="seek-bar" onclick="updateSeekBar(event)">
          <div class="seek-bar-fill" id="seek-bar-fill"></div>
          <div class="seek-bar-thumb" id="seek-bar-thumb"></div>
        </div><button onclick="seekForward()">+</button>
      </div><audio id="music-player" src="/music.mp3"></audio>
    </div>
  </div>
  <script>

  // Code JavaScript pour masquer l'overlay après quelques secondes
  setTimeout(function() {
    var overlay = document.getElementById('overlay');
    overlay.classList.add('hide');
  }, 3000); // Masque l'overlay après 3 secondes

  // Votre code JavaScript existant pour le lecteur de musique va ici
  var audio = document.getElementById('music-player');
  var timeRemainingElement = document.getElementById('time-remaining');
  var playPauseButton = document.querySelector('.play-pause-button');
  var seekBar = document.getElementById('seek-bar');
  var seekBarFill = document.getElementById('seek-bar-fill');
  var seekBarThumb = document.getElementById('seek-bar-thumb');
  var updateTimeInterval;

  function togglePlayPause() {
    if (audio.paused) {
      audio.play();
      playPauseButton.innerHTML = '&#10074;&#10074;'; // Symbole de pause
      updateTimeInterval = setInterval(updateTimeRemaining, 1000);
    } else {
      audio.pause();
      playPauseButton.innerHTML = '&#9658;'; // Symbole de lecture
      clearInterval(updateTimeInterval);
    }
  }

  function updateTimeRemaining() {
    var timeRemaining = audio.duration - audio.currentTime;
    var minutes = Math.floor(timeRemaining / 60);
    var seconds = Math.floor(timeRemaining % 60);
    if (seconds < 10) seconds = '0' + seconds;
    timeRemainingElement.innerText = 'Temps restant : ' + minutes + ':' + seconds;

    // Met à jour la position du curseur de la barre de progression
    var seekBarWidth = seekBar.offsetWidth;
    var currentTimePercentage = (audio.currentTime / audio.duration) * 100;
    var thumbPosition = (currentTimePercentage / 100) * seekBarWidth;
    seekBarFill.style.width = currentTimePercentage + '%';
    seekBarThumb.style.left = thumbPosition + 'px';
  }

  function updateSeekBar(event) {
    var seekBarWidth = seekBar.offsetWidth;
    var clickPosition = event.clientX - seekBar.getBoundingClientRect().left;
    var clickPercentage = (clickPosition / seekBarWidth) * 100;
    seekBarFill.style.width = clickPercentage + '%';
    var newTime = (clickPercentage / 100) * audio.duration;
    audio.currentTime = newTime;
  }

  function seekBackward() {
    audio.currentTime -= 10; // Reculer de 10 secondes
  }

  function seekForward() {
    audio.currentTime += 10; // Avancer de 10 secondes
  }

  audio.addEventListener('ended', function() {
    clearInterval(updateTimeInterval);
    timeRemainingElement.innerText = 'Temps restant : 00:00';
    playPauseButton.innerHTML = '&#9658;'; // Symbole de lecture
  });

  audio.addEventListener('loadedmetadata', function() {
    updateTimeRemaining();
  });
  </script>
  <link rel="icon" href="./public/mahiro_flex.ico">
  <link rel="stylesheet" href="./styles/style.css">
  <link href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" rel="stylesheet" crossorigin="">
  <div class="container">
    <div class="profile-border box-color">
      <div class="profile box-color">
        <div class="banner"><img loading="lazy" id="banner-image" src="./public/banner.webp" alt="banner"></div>
        <div class="main-header">
          <div class="image">
            <div class="avatar">
              <img loading="lazy" class="box-color" id="avatar-image" alt="av" aria-hidden="true" src="./public/av.webp">
              <div class="status box-color"><img id="status-image" src="./public/status/offline.svg" alt="offline"></div>
            </div>
          </div>
          <div class="badges box-color" id="badges">
            <div class="badges-right">
              <a class="tooltip" aria-label="HypeSquad Bravery"><img alt="hypesquad-bravery" src="./public/badges/hypesquad-bravery.svg"></a> <a class="tooltip" id="active-developer" aria-label="Active Developer"><img alt="active-developer" src="./public/badges/active-developer.svg"></a> <a class="tooltip" aria-label="Abonné depuis 8 avr. 2023"><img alt="nitro" src="./public/badges/nitro.svg"></a> <a class="tooltip" aria-label="Abonné depuis 9 avr. 2023"><img alt="boost-12-month" src="./public/badges/boost-12-month.svg"></a> <a class="tooltip" aria-label="Ancien Nom : Karbone#2518"><img alt="legacy-username" src="./public/badges/legacy-username.svg"></a>
            </div>
            <div class="badges-left"></div>
          </div>
        </div>
        <div class="card box-color">
          <div class="name-box">
            <span class="display-name">Cano</span> <span class="username">karbone.</span> <span class="pronouns">🇹🇷 Al-Turkmani</span>
            <div class="custom-status">
              <img id="custom-status-emoji" alt="">
              <p class="custom-status-text"></p>
            </div>
          </div>
          <div class="body">
            <div class="content">
              <div class="about-section">
                <div class="title-body">
                  ABOUT ME
                </div><span class="about-me">I'm Mizu🌸 from</span>
                <div class="flag">
                  <span class="about-me"><img src="./public/icons/flag-for-flag-vietnam-svgrepo-com.svg" alt="flag-for-flag-vietnam-svgrepo-com"></span>
                </div><span class="about-me">a Hikikomori plus NEET, and I enjoy playing video games 🎮, watching anime, reading manga 🗾, and occasionally tinkering with with random stuff 💻. I'm quite shy 👉👈, so it would be really nice if you're the one who takes the initiative to be friends with me (≩ᴗ≨).<br>
                <br>
                I'm currently the owner 👑 of a small <a href="https://discord.com/" target="_blank">Discord</a> server called <a href="https://discord.gg/XCgDcusrNj" target="_blank">N.E.E.T</a> and I hope you'll join and play some games with me on <a href="https://steamcommunity.com/id/karbone./" target="_blank">Steam</a>.</span>
              </div>
              <div class="title-body">
                ROLES
              </div>
              <div class="roles-body">
                <div class="rol rosepink">
                  <span>ニート</span>
                </div>
                <div class="rol softpink">
                  <span>Developpeur Web</span>
                </div>
                <div class="rol green">
                  <span>Gamer</span>
                </div>
                <div class="rol blue">
                  <span>ICTU Student</span>
                </div>
              </div>
              <div class="divider social-divider"></div>
              <div class="title-body">
                CONNECTIONS
              </div>
              <div class="socials">
                <div class="column">
                  <a class="platform" href="https://www.instagram.com/cn.isslam/" rel="noreferrer noopener" target="_blank"><img class="platform-icon" alt="instagram" aria-hidden="true" src="./public/platforms/instagram.svg">
                  <div class="text-base platform-username">
                    cn.isslam
                  </div>
                  <div><img alt="link" id="link" aria-hidden="true" src="./public/icons/link.svg" class="connect"></div></a> <a class="platform" href="https://open.spotify.com/user/wbaftxfvwzh37p9eujc3s2m2r" rel="noreferrer noopener" target="_blank"><img class="platform-icon" alt="spotify" aria-hidden="true" src="./public/platforms/spotify.svg">
                  <div class="text-base platform-username">
                    الماتريدية
                  </div>
                  <div href="http://fb.com/karbone./" rel="noreferrer noopener" target="_blank"><img alt="link" id="link" aria-hidden="true" src="./public/icons/link.svg" class="connect"></div></a>
                </div>
                <div class="column">
                  <a class="platform" href="https://github.com/karbone-dev" rel="noreferrer noopener" target="_blank"><img class="platform-icon" alt="github" aria-hidden="true" src="./public/platforms/github.svg">
                  <div class="text-base platform-username">
                    Karbone-DEV
                  </div>
                  <div><img alt="link" id="link" aria-hidden="true" src="./public/icons/link.svg" class="connect"></div></a> <a class="platform" href="https://discord.gg/XCgDcusrNj" rel="noreferrer noopener" target="_blank"><img class="platform-icon" alt="discord" aria-hidden="true" src="./public/platforms/discord.svg">
                  <div class="text-base platform-username">
                    Discord Server
                  </div>
                  <div class=""><img alt="link" id="link" aria-hidden="true" src="./public/icons/link.svg" class="connect"></div></a>
                </div>
              </div>
              <div class="chat-container">
                <input type="text" id="message-input" placeholder="Message @Mizu">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="./scripts/script_static.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</body>
</html>
```

MY CSS:

```css
@import url(https://cdn.jsdelivr.net/gh/Overimagine1/old-discord-font/source.min.css);

* {
  font-family: "Whitney", sans-serif;
  transition: width 0.5s ease, height 0.5s ease;
}

:root {
  --primary-h-top: 0deg; /* Teinte reste à 0 pour le gris */
  --primary-s-top: 0%; /* Saturation reste à 0 pour le gris */
  --primary-l-top: 10%; /* Luminosité plus élevée pour le gris clair */
  --primary-h-bottom: 0deg; /* Teinte reste à 0 pour le gris */
  --primary-s-bottom: 1%; /* Saturation reste à 0 pour le gris */
  --primary-l-bottom: 1%; /* Luminosité plus faible pour le gris foncé */
  --text-color: black; /* Couleur du texte en noir */
  --box-shadow-color: rgba(0, 0, 0, 0.1); /* Ombre portée de couleur noire avec une opacité de 0,1 */
}



::-webkit-scrollbar {
  width: 0.3rem;
  height: auto;
  scrollbar-width: thin;
  /* scrollbar-gutter: unset; */
  border-radius: 50%;
}

::-webkit-scrollbar-track {
  background-color: transparent;
}

::-webkit-scrollbar-thumb {
  background-color: hsl(var(--primary-h-top), 45%, 50%, 0.1);
  border-radius: 10px;
}

/* Disable drag and drop on all elements */
* {
  -webkit-user-drag: none;
  -khtml-user-drag: none;
  -moz-user-drag: none;
  -o-user-drag: none;
}

html {
  scroll-behavior: smooth;
}

img {
  opacity: 0;
  animation: fadeIn 1s ease-in forwards;
}

.about-section a {
  color: #00aff4;
  text-decoration: none;
}

.about-section a:hover {
  text-decoration: underline;
}

body {
  padding: 0;
  margin: 0;
}

.box-color {
  background: linear-gradient(to bottom,
      hsl(var(--primary-h-top), var(--primary-s-top), var(--primary-l-top)),
      hsl(var(--primary-h-bottom), var(--primary-s-bottom), var(--primary-l-bottom)));
}

.container {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100vh;
}

.container::before {
  content: "";
  position: fixed;
  margin: -15px;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url("../public/bg.webp");
  background-repeat: no-repeat;
  z-index: -1;
  filter: blur(5px);
  /* make img darker */
  background-color: rgba(0, 0, 0, 0.5);
  background-blend-mode: darken;
  /* end */
  background-size: cover;
  background-position: center;
}

.profile-border {
  box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.1);
  padding: 5px;
  position: relative;
  display: flex;
  flex-direction: column;
  max-height: calc(100% - 100px);
  border-radius: 8px;
  margin: 0 auto;
}

.profile {
  z-index: 1;
  position: relative;
  display: flex;
  flex-direction: column;
  /* overflow-x: hidden; */
  --primary-s-top: 46%;
  --primary-l-top: 99%;
  --primary-s-bottom: 47%;
  --primary-l-bottom: 60%;
  width: 600px;
  max-height: calc(100vh - 100px);
  color: #000000;
  border-radius: 8px;
  margin: 0 auto;
  background: linear-gradient(
    #1a1a1a, 
    #0a070a
  );
}


.profile .banner {
  width: 100%;
  height: 190px;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.profile .banner img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  border-top-left-radius: 5px;
  border-top-right-radius: 5px;
}

.avatar {
  --primary-s-top: 42%;
  --primary-l-top: 95%;
  --primary-s-bottom: 44%;
  --primary-l-bottom: 94%;
  display: flex;
  align-items: center;
  justify-content: center;
  position: absolute;
  border-radius: 50%;
  top: 120px;
  left: 16px;
}

.avatar #avatar-image {
  width: 120px;
  height: 120px;
  border-radius: 50%;
  padding: 8px;
  background-color: hsl(300, 9%, 7%);
  --primary-s-top: %;
  --primary-l-top: %;
  --primary-s-bottom: %;
  --primary-l-bottom: %;
}

.avatar-decoration {
  width: 1700px;
  height: 170px;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

.status {
  max-width: 34px;
  max-height: 44px;
  -webkit-transform: translate(50%, 50%);
  transform: translate(50%, 50%);
  --primary-s-top: 100%;
  --primary-l-top: 0%;
  --primary-h-bottom: var(--primary-h-top);
  --primary-s-bottom: 100%;
  --primary-l-bottom: 1%;
  position: absolute;
  bottom: 14.64%;
  right: 14.64%;
  border-radius: 50%;
}

#status-image {
  width: 20px;
  height: 20px;
  padding: 7px;
  border-radius: 50%;
}

.badges {
  display: flex;
  flex-direction: row-reverse;
  width: fit-content;
  padding: 2px;
  --primary-s-top: 1%;
  --primary-l-top: 20%;
  --primary-h-bottom: var(
  --primary-h-top);
  --primary-s-bottom: 1%;
  --primary-l-bottom: 1%;
  border-radius: 10px;
  position: absolute;
  top: 219px;
  left: 160px;
}

.badges img {
  width: 26px;
  height: 26px;
}

.badges .badges-left {
  width: fit-content;
  height: 26px;
}

.badges .badges-left img {
  opacity: 100%;
  animation: none;
}

.badges .badges-right {
  display: flex;
  flex-direction: row;
  width: fit-content;
  height: 26px;
}

.tooltip {
  display: block;
  flex-direction: row;
  position: relative;
  width: 26px;
  height: 26px;
}

.tooltip:hover::after {
  content: attr(aria-label);
  position: absolute;
  top: -77px;
  left: 50%;
  transform: translateX(-50%);
  background-color: #111214;
  color: #fff;
  padding: 10px;
  border-radius: 5px;
}

.tooltip:hover::before {
  content: "";
  position: absolute;
  top: -19px;
  left: 50%;
  transform: translateX(-50%);
  border: 5px solid transparent;
  border-top-color: #111214;
}

.card {
  position: relative;
  margin: 80px 16px 16px;
  --primary-h-top: 0deg; /* Teinte reste à 0 pour le gris */
  --primary-s-top: 0%; /* Saturation reste à 0 pour le gris */
  --primary-l-top: 11%; /* Luminosité plus élevée pour le gris clair */
  --primary-h-bottom: 0deg; /* Teinte reste à 0 pour le gris */
  --primary-s-bottom: 1%; /* Saturation reste à 0 pour le gris */
  --primary-l-bottom: 1%; /* Luminosité plus faible pour le gris foncé */
  --text-color: rgb(255, 255, 255); /* Couleur du texte en noir */
  border-radius: 5px;
}

.name-box {
  width: fit-content;
  position: relative;
  display: flex;
  flex-direction: column;
  margin: 20px 20px 0px 20px;
  padding-left: 5px;
}

.display-name {
  font-size: 20px;
  color: var(--text-color);
  font-weight: bolder;
}

.username {
  color: var(--text-color);
  font-weight: 600;
  border-radius: 50%;
}

.pronouns {
  color: var(--text-color);
  font-weight: 400;
  font-size: 14px;
  margin: 3px 0px 5px 0px;
}

.custom-status {
  display: flex;
  width: fit-content;
  flex-direction: row;
  justify-items: center;
  align-items: center;
  padding: 0px 0px 10px 0px;
}

.custom-status img {
  width: fit-content;
  height: fit-content;
}

.custom-status .custom-status-text {
  margin: 0px;
  padding: 0px;
  align-items: center;
  display: flex;
  color: var(--text-color);
  font-weight: 400;
}

.about-me {
  overflow-wrap: break-word;
  font-size: 14px;
  line-height: 20px;
  color: var(--text-color);
  font-weight: 500;
}

.flag {
  display: inline-block;
  position: relative;
  width: 22px;
  height: 14px;
  /* margin-right: 22px; */
}

.flag img {
  position: absolute;
  width: 20px;
  height: 20px;
}

.divider {
  height: 0px;
  margin-top: 5px;
  margin-bottom: 0px;
  background-color: transparent;
}

.body {
  padding: 0 20px 16px 20px;
  max-height: calc(100vh - 530px);
}

.body .title-body {
  font-weight: 700;
  color: var(--text-color);
  font-size: 14px;
  line-height: 16px;
  margin-bottom: 8px;
}

.body .roles-body {
  margin-bottom: 10px;
}

.content {
  border-top: 1px solid var(--box-shadow-color);
  padding-top: 12px;
  overflow-x: hidden;
  position: relative;
  display: flex;
  flex-direction: column;
  max-height: calc(100vh - 530px);
  scroll-snap-type: y mandatory;
  -ms-overflow-style: none;
  scrollbar-width: none;
  padding: 5px;
}

.about-section {
  margin-bottom: 16px;
  margin-top: 5px;
}

.roles-body {
  -ms-flex-wrap: wrap;
  margin: 1px;
  flex-wrap: wrap;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}

.roles-body .rol {
  border-radius: 4px;
  background: linear-gradient(to bottom,
      hsl(var(--primary-h-top), var(--primary-s-top), var(--primary-l-top)),
      hsl(var(--primary-h-bottom), var(--primary-s-bottom), var(--primary-l-bottom)));
  --primary-s-top: 10%;
  --primary-l-top: 5%;
  --primary-h-bottom: var(--primary-h-top);
  --primary-s-bottom: 12%;
  --primary-l-bottom: 10%;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  margin: 0 4px 4px 0;
  padding: 4px;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  height: 22px;
  font-size: 12px;
  font-weight: 500;
  box-shadow: 0 0 0 1px var(--box-shadow-color);
}

.roles-body .rol span {
  color: var(--text-color);
  margin-left: 4px;
  margin-right: 4px;
}

.social-divider {
  margin-bottom: 0;
}

.socials {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-pack: justify;
  -ms-flex-pack: justify;
  justify-content: space-between;
}

.platform {
  width: 225px;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  margin-bottom: 20px;
  padding: 12px;
  border-radius: 4px;
  -webkit-box-align: center;
  -ms-flex-align: center;
  align-items: center;
  box-shadow: 0 0 0 1px var(--box-shadow-color);
  text-decoration: none;
}

.platform-username {
  color: var(--text-color);
  font-size: 16px;
  font-weight: 600;
  margin-left: 10px;
  -webkit-box-flex: 1;
  -ms-flex-positive: 1;
  flex-grow: 1;
}

.platform::hover {
  text-decoration: none;
}

.platform-icon {
  width: 24px;
  height: 24px;
}

.connect {
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
  width: 20px;
  height: 20px;
  -webkit-filter: invert(86%) sepia(5%) saturate(136%) hue-rotate(177deg) brightness(70%) contrast(70%);
  filter: invert(86%) sepia(5%) saturate(136%) hue-rotate(177deg) brightness(70%) contrast(70%);
}

.connect:hover {
  -webkit-filter: invert(100%) sepia(100%) saturate(0%) hue-rotate(288deg) brightness(0%) contrast(0%);
  filter: invert(100%) sepia(100%) saturate(0%) hue-rotate(288deg) brightness(0%) contrast(0%);
}

.softpink {
  color: #f8bbd0;
}

.rosepink {
  color: #ecdcd4;
}

.green {
  color: #1ed760;
}

.blue {
  color: #00aff4;
}

.chat-container {
  width: 494px;
  max-width: 514px;
  margin-top: 0px;
  margin-bottom: 10px;
  box-shadow: 0 0 0 1px var(--box-shadow-color);
  padding: 10px 10px 10px 10px;
  border-radius: 5px;
}

.chat-container {
  display: none !important;
}

#message-input {
  background-color: transparent;
  width: 100%;
  padding: 5px;
  border: none;
  outline: none;
  font-size: 16px;
  font-weight: 500;
}

@media (width <=640px) {
  .container::before {
    background-image: url("../public/bg_mobile.webp");
    margin: -2px;
    filter: blur(2px);
    background-color: rgba(0, 0, 0, 0.5);
    background-blend-mode: darken;
  }

  .profile {
    width: 300px;
  }

  .profile .banner {
    height: 100px;
  }

  .badges {
    top: 120px;
    right: 16px;
    left: unset;
    flex-direction: row-reverse;
  }

  .avatar {
    top: 55px;
  }

  .avatar #avatar-image {
    width: 86px;
    height: 86px;
  }

  .avatar-decoration {
    width: 130px;
    height: 130px;
  }

  .name-box {
    width: 236px;
    margin: 16px 16px 10px 16px;
  }

  .body {
    padding: 0 16px 16px 16px;
  }

  .card {
    margin: 70px 16px 16px;
  }

  .socials {
    display: block;
  }

  .platform {
    width: 196px;
  }

  .chat-container {
    width: 200px;
  }
}

@keyframes fadeIn {
  0% {
    opacity: 0;
  }

  100% {
    opacity: 1;
  }
}
```

### Steps to Reproduce

Just add my website in vercel and you will see that the website don't work
