### DISCUSSION TITLE
Meilisearch and Vercel

### DISCUSSION THREAD

**Discussion by GuillaumeDelore** [vercel/community#7455] [Help]
### Summary

Hello all,

I test Meilisearch for use with my nextjs project on Vercel. One key aspect is to be able to synchronize Meilisearch with my PostGreSQL database on Vercel. 

Meilisearch has a tutorial for it https://www.meilisearch.com/docs/guides/database/meilisync_postgresql , but not directly for usage with Vercel. Given Vercel technical environment, is it possible to reproduce this tutorial and synchronize Meilisearch with Vercel ?

Thank you in advance

### Steps to Reproduce

please have a look at the following link: https://www.meilisearch.com/docs/guides/database/meilisync_postgresql

**Comment by versecafe** [comment]
@GuillaumeDelore  There should be no issue doing this just configure the PG Yaml for Vercel

```yml
source:
  type: postgres
  host: us-east-1.aws.neon.tech
  port: 5432
  database: POSTGRESQL_DATABASE_NAME
  user: POSTGRESQL_USERNAME
  password: POSTGRESQL_PASSWORD
```

You can get the needed data at `https://vercel.com/[team]/[project]/stores/postgres/[store ID]/data`

[a comment by an automated account is not shown]
