### DISCUSSION TITLE
monorepo vercel cli deploy error

### DISCUSSION THREAD

**Discussion by productdevbook** [vercel/community#851] [Help] [answered]
iam used turbomonorepo 

![image](https://user-images.githubusercontent.com/38668796/189930484-6a2e303e-96a1-4a01-8d08-a1dbc703edcd.png)

![image](https://user-images.githubusercontent.com/38668796/189930529-5ad4f009-518b-4ff9-9113-b2fb84c8bac4.png)

vercel.json

```
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "github": {
    "enabled": false,
    "silent": true,
    "autoJobCancelation": true
  }
}
```

error logs
```
Error: The specified Root Directory "apps/vue-web" does not exist. Please update your Project Settings. Learn More: https://vercel.com/docs/build-step#root-directory
```

but same setting auto vercel github preview working.

**Comment by swarnava** [comment, marked as answer]
Hi,

Could you share your project link or Deployment ID?

**Reply by productdevbook** [reply]
deployment id -> GLBVMmEQaR6GcowNmY9tcStussjZ

**Reply by swarnava** [reply]
I can see that `main` is production branch but these Production deployments are being deployed using different branch. What is your current workflow? Are you using CLI / GitHub Action or some custom script to deploy?

**Reply by productdevbook** [reply]
yes, iam used github action

```

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Vercel Action
      uses: BetaHuhn/deploy-to-vercel-action@v1.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          PRODUCTION: true
```

**Reply by productdevbook** [reply]
now change is fixed. interested. did you do something

```
name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: 📦 Install ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
```
